### ISSUE TITLE
Unhandled termios exception

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#1001]
Thanks for the extra info @andychu - I'll see if when i free up I can poke around the dev build. This would be my first change working with oil source, so it may be a bit to ambitious but i'll see. Changing calls for `posix.read` and handling with `try/except` seems doable if I can get up to speed with the tooling / how I would add tests etc.

In the meantime I did manage a workaround via `wait` like:
```sh
#!/usr/bin/env osh

trap handler HUP

handler() {
  echo works
}

echo before
read var & wait
echo after
```

Sending `pkill -HUP osh` interrupts the read as desired this way.. the only unfortunate bit with this workaround is after quitting the script, to STDERR, a really ugly message get displayed:

```sh
Traceback (most recent call last):
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 328, in _cpython_main_hook
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 301, in main
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 292, in AppBundleMain
  File "/home/andy/git/oilshell/oil/core/shell.py", line 675, in Main
  File "/home/andy/git/oilshell/oil/core/main_loop.py", line 330, in Batch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1495, in ExecuteAndCatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1342, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 988, in _Dispatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1398, in _ExecuteList
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1342, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 652, in _Dispatch
  File "/home/andy/git/oilshell/oil/core/executor.py", line 295, in RunBackgroundJob
  File "/home/andy/git/oilshell/oil/core/process.py", line 880, in Start
  File "/home/andy/git/oilshell/oil/core/process.py", line 704, in Run
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1495, in ExecuteAndCatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1342, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 636, in _Dispatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 477, in _RunSimpleCommand
  File "/home/andy/git/oilshell/oil/core/executor.py", line 230, in RunSimpleCommand
  File "/home/andy/git/oilshell/oil/core/executor.py", line 126, in RunBuiltin
  File "/home/andy/git/oilshell/oil/osh/builtin_misc.py", line 328, in Run
  File "/home/andy/git/oilshell/oil/core/pyos.py", line 119, in Restore
termios.error: (5, 'I/O error')
FATAL: couldn't import from app bundle '/usr/bin/oil.ovm' (1)
Stripping the oil.ovm binary may cause this error.even
See https://github.com/oilshell/oil/issues/47
```

This message shows up after the script is exited right upon typing the next character into the shell! Strange..

_Originally posted by @mil in https://github.com/oilshell/oil/issues/986#issuecomment-964386985_

**Comment by andychu** [comment]
OK I can reproduce this.  Weirdly it happens when you hit ENTER afterward

**Comment by andychu** [comment]
Released! https://www.oilshell.org/blog/2021/11/release-0.9.4.html
