### ISSUE TITLE
catch TypeError consistently

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#1124]
There is a oneoff for `const`, but not `var`

I think we can now raise `error.Expr` and it will be caught by `try`

```
$ var x = {} + []
Traceback (most recent call last):
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 360, in <module>
    sys.exit(main(sys.argv))
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 303, in main
    return AppBundleMain(argv)
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 262, in AppBundleMain
    loader, line_input)
  File "/home/andy/git/oilshell/oil/core/shell.py", line 647, in Main
    prompt_plugin, errfmt)
  File "/home/andy/git/oilshell/oil/core/main_loop.py", line 257, in Interactive
    is_return, _ = cmd_ev.ExecuteAndCatch(node)
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1566, in ExecuteAndCatch
    status = self._Execute(node)
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1404, in _Execute
    status = self._Dispatch(node, cmd_st)
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 809, in _Dispatch
    py_val = self.expr_ev.EvalExpr(node.rhs)
  File "/home/andy/git/oilshell/oil/oil_lang/expr_eval.py", line 196, in EvalExpr
    return self._EvalExpr(node)
  File "/home/andy/git/oilshell/oil/oil_lang/expr_eval.py", line 318, in _EvalExpr
    return left + right
TypeError: unsupported operand type(s) for +: 'dict' and 'list'
andy@lenny:~/git/oilshell/oil$
andy@lenny:~/git/oilshell/oil$
andy@lenny:~/git/oilshell/oil$
andy@lenny:~/git/oilshell/oil$
andy@lenny:~/git/oilshell/oil$
andy@lenny:~/git/oilshell/oil$
andy@lenny:~/git/oilshell/oil$
andy@lenny:~/git/oilshell/oil$
andy@lenny:~/git/oilshell/oil$
andy@lenny:~/git/oilshell/oil$ bin/osh
[osh] lenny ~/git/oilshell/oil$ const x = {} + []
  const x = {} + []
        ^
[ interactive ]:1: fatal: Type error in expression: unsupported operand type(s) for +: 'dict' and 'list'

```

**Comment by andychu** [comment]
https://www.oilshell.org/release/0.10.1/
