### ISSUE TITLE
mycpp build errors hard to find

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#1154]
It was hidden here ...

How do I get ninja to surface these errors?

There is too much spew

```
$ head *
==> strings.py.log.txt <==
Traceback (most recent call last):
  File "examples/strings.py", line 8, in <module>
    from mylib import log
  File "/home/andy/git/oilshell/oil/mycpp/mylib.py", line 9, in <module>
    from pylib import collections_
ImportError: No module named pylib

```

**Comment by andychu** [comment]
Just ran into this.  The annoying thing is that the `_build/cpp/osh_eval.h` files get truncated, and the error message is in `_devbuild/tmp/osh_eval_raw.cc`  !   BAD!

**Comment by andychu** [comment]
- OK errors go to stderr now
- `ninja -j 1 mycpp-all` is useful.  Updated  https://github.com/oilshell/oil/wiki/Oil-Dev-Cheat-Sheet
