### ISSUE TITLE
Oil parser crashes on eggex /!/

### ISSUE THREAD

**Issue by Aloso** [oilshell/oil#1225]
**To reproduce**

Open oil shell and enter

```
var _ = /!/
```

And oil crashes with the following error message:

<details>
<summary><b>Click to expand</b></summary>

```
Traceback (most recent call last):
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 325, in _cpython_main_hook
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 298, in main
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 289, in AppBundleMain
  File "/home/andy/git/oilshell/oil/core/shell.py", line 668, in Main
  File "/home/andy/git/oilshell/oil/core/main_loop.py", line 210, in Interactive
  File "/home/andy/git/oilshell/oil/osh/cmd_parse.py", line 2380, in ParseInteractiveLine
  File "/home/andy/git/oilshell/oil/osh/cmd_parse.py", line 2223, in _ParseCommandLine
  File "/home/andy/git/oilshell/oil/osh/cmd_parse.py", line 2142, in ParseAndOr
  File "/home/andy/git/oilshell/oil/osh/cmd_parse.py", line 2153, in _ParseAndOr
  File "/home/andy/git/oilshell/oil/osh/cmd_parse.py", line 2085, in ParsePipeline
  File "/home/andy/git/oilshell/oil/osh/cmd_parse.py", line 1955, in ParseCommand
  File "/home/andy/git/oilshell/oil/osh/word_parse.py", line 1035, in ParseVarDecl
  File "/home/andy/git/oilshell/oil/frontend/parse_lib.py", line 346, in ParseVarDecl
  File "/home/andy/git/oilshell/oil/oil_lang/expr_to_ast.py", line 676, in MakeVarDecl
  File "/home/andy/git/oilshell/oil/oil_lang/expr_to_ast.py", line 614, in Expr
  File "/home/andy/git/oilshell/oil/oil_lang/expr_to_ast.py", line 226, in _Tuple
  File "/home/andy/git/oilshell/oil/oil_lang/expr_to_ast.py", line 614, in Expr
  File "/home/andy/git/oilshell/oil/oil_lang/expr_to_ast.py", line 614, in Expr
  File "/home/andy/git/oilshell/oil/oil_lang/expr_to_ast.py", line 103, in _AssocBinary
  File "/home/andy/git/oilshell/oil/oil_lang/expr_to_ast.py", line 614, in Expr
  File "/home/andy/git/oilshell/oil/oil_lang/expr_to_ast.py", line 103, in _AssocBinary
  File "/home/andy/git/oilshell/oil/oil_lang/expr_to_ast.py", line 614, in Expr
  File "/home/andy/git/oilshell/oil/oil_lang/expr_to_ast.py", line 614, in Expr
  File "/home/andy/git/oilshell/oil/oil_lang/expr_to_ast.py", line 614, in Expr
  File "/home/andy/git/oilshell/oil/oil_lang/expr_to_ast.py", line 614, in Expr
  File "/home/andy/git/oilshell/oil/oil_lang/expr_to_ast.py", line 103, in _AssocBinary
  File "/home/andy/git/oilshell/oil/oil_lang/expr_to_ast.py", line 614, in Expr
  File "/home/andy/git/oilshell/oil/oil_lang/expr_to_ast.py", line 103, in _AssocBinary
  File "/home/andy/git/oilshell/oil/oil_lang/expr_to_ast.py", line 614, in Expr
  File "/home/andy/git/oilshell/oil/oil_lang/expr_to_ast.py", line 103, in _AssocBinary
  File "/home/andy/git/oilshell/oil/oil_lang/expr_to_ast.py", line 614, in Expr
  File "/home/andy/git/oilshell/oil/oil_lang/expr_to_ast.py", line 103, in _AssocBinary
  File "/home/andy/git/oilshell/oil/oil_lang/expr_to_ast.py", line 614, in Expr
  File "/home/andy/git/oilshell/oil/oil_lang/expr_to_ast.py", line 103, in _AssocBinary
  File "/home/andy/git/oilshell/oil/oil_lang/expr_to_ast.py", line 614, in Expr
  File "/home/andy/git/oilshell/oil/oil_lang/expr_to_ast.py", line 103, in _AssocBinary
  File "/home/andy/git/oilshell/oil/oil_lang/expr_to_ast.py", line 614, in Expr
  File "/home/andy/git/oilshell/oil/oil_lang/expr_to_ast.py", line 614, in Expr
  File "/home/andy/git/oilshell/oil/oil_lang/expr_to_ast.py", line 614, in Expr
  File "/home/andy/git/oilshell/oil/oil_lang/expr_to_ast.py", line 309, in _Atom
  File "/home/andy/git/oilshell/oil/oil_lang/expr_to_ast.py", line 1505, in _Regex
  File "/home/andy/git/oilshell/oil/oil_lang/expr_to_ast.py", line 1521, in _Regex
  File "/home/andy/git/oilshell/oil/oil_lang/expr_to_ast.py", line 1420, in _ReAtom
IndexError: list index out of range
FATAL: couldn't import from app bundle '/usr/bin/oil.ovm' (1)
Stripping the oil.ovm binary may cause this error.
See https://github.com/oilshell/oil/issues/47
```

</details>

**Comment by andychu** [comment]
Thanks for the report!  I just fixed this, it was an error/typo in the grammar.

**Comment by andychu** [comment]
Fix released: http://www.oilshell.org/release/0.12.0/

Thanks for trying Eggex, and let me know if you find any other problems!
