### ISSUE TITLE
mycpp/examples/modules crashes -- "vtable?"

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#1228]
- #1190 

Not sure what this is about ... I thought the GC would correctly handle vtables.  

Did it somehow get screwed up?

```
Starting program: /home/andy/git/oilshell/oil/_bin/cxx-testgc/mycpp-examples/modules
func1
CONST module2
func2
CONST module1
--> COLLECT with 3 roots
--> COLLECT with 3 roots
white dog: meow
--> COLLECT with 3 roots
cat
--> COLLECT with 3 roots
--> COLLECT with 3 roots
brown sphinx

Program received signal SIGSEGV, Segmentation fault.
0x0000555555758c08 in vtable for module1::Cat ()
(gdb) bt
#0  0x0000555555758c08 in vtable for module1::Cat ()
#1  0x00005555555559f8 in modules::run_tests () at _test/gen-mycpp/modules.cc:173
#2  0x0000555555555bec in main (argc=1, argv=0x7fffffffe5a8) at _test/gen-mycpp/modules.cc:224

```

**Comment by andychu** [comment]
Done!
