### ISSUE TITLE
race condition in Soil

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#1248]
I thought I got rid of this?

https://github.com/oilshell/oil/runs/7462653956?check_suite_focus=true

```
 /home/travis_admin/travis-ci.oilshell.org/github-jobs/2022-07-22__05-22-23.json
Traceback (most recent call last):
  File "/home/travis_admin/soil-web/soil/web.py", line 406, in <module>
    main(sys.argv)
  File "/home/travis_admin/soil-web/soil/web.py", line 334, in main
    rows = list(ParseJobs(sys.stdin))
  File "/home/travis_admin/soil-web/soil/web.py", line 127, in ParseJobs
    with open(tsv_path) as f:
IOError: [Errno 2] No such file or directory: '/home/travis_admin/travis-ci.oilshell.org/github-jobs/2022-07-22__05-22-23.tsv'
Error: Process completed with exit code 1.
```

**Comment by andychu** [comment]
That was on app_tests

---

This one is on dummy_orig

https://github.com/oilshell/oil/runs/7588306404?check_suite_focus=true

```
/home/travis_admin/travis-ci.oilshell.org/github-jobs/2022-07-29__15-57-09.json
/home/travis_admin/travis-ci.oilshell.org/github-jobs/2022-07-30__01-34-20.json
status=0 0 0
renamed '253062.index.html' -> '/home/travis_admin/travis-ci.oilshell.org/github-jobs/index.html'
ls: cannot access '/home/travis_admin/travis-ci.oilshell.org/github-jobs/2022-07-22__22-28-29.json': No such file or directory
```

**Comment by andychu** [comment]
Happened on `dummy_orig`

```
renamed '71621.index.html' -> '/home/travis_admin/travis-ci.oilshell.org/github-jobs/index.html'
ls: cannot access '/home/travis_admin/travis-ci.oilshell.org/github-jobs/2022-08-31__18-20-10.json': No such file or directory
ls: cannot access '/home/travis_admin/travis-ci.oilshell.org/github-jobs/2022-08-31__18-20-43.json': No such file or directory
```

**Comment by andychu** [comment]
Get rid of JSON spew too
