### ISSUE TITLE
Oil crashes when calling missing method after `_`

### ISSUE THREAD

**Issue by pdebelak** [oilshell/oil#1253]
Since the `oil` documentation can sometimes be incomplete, I've been trying to experiment with various functions and methods to figure out how they work (and also to try to figure what things mentioned in the tour of oil are functions or methods).

Here is me trying to see if `sub` is a method and, if so, how to use it:

```
oil$ const val = "hello"
oil$ val.sub(/ alpha /, "i")
  val.sub(/ alpha /, "i")
         ^
[ interactive ]:2: Space required before (
oil$ val.sub (/ alpha /, "i")
  val.sub (/ alpha /, "i")
          ^
[ interactive ]:3: fatal: Unexpected typed args passed to external command 'val.sub'
oil$ _ val.sub(/ alpha /, "i")
Traceback (most recent call last):
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 325, in _cpython_main_hook
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 298, in main
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 289, in AppBundleMain
  File "/home/andy/git/oilshell/oil/core/shell.py", line 641, in Main
  File "/home/andy/git/oilshell/oil/core/main_loop.py", line 288, in Interactive
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1652, in ExecuteAndCatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1482, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 986, in _Dispatch
  File "/home/andy/git/oilshell/oil/oil_lang/expr_eval.py", line 198, in EvalExpr
  File "/home/andy/git/oilshell/oil/oil_lang/expr_eval.py", line 549, in _EvalExpr
  File "/home/andy/git/oilshell/oil/oil_lang/expr_eval.py", line 576, in _EvalExpr
AttributeError: 'str' object has no attribute 'sub'
FATAL: couldn't import from app bundle '/Users/pdebelak/.local/bin/oil.ovm' (1)
Stripping the oil.ovm binary may cause this error.
See https://github.com/oilshell/oil/issues/47
```

A shorter repro case is just `oil -c '_ "hello".sub(1)'` which also crashes with a stacktrace.

`/Users/pdebelak/.local/bin/oil.ovm` does exist on my system (which is the same place `osh` and `oil` are installed) if that is relevant here.

**Comment by andychu** [comment]
Released: https://www.oilshell.org/release/0.12.3/

Thanks for trying it and let me know if you have other problems / questions!
