### ISSUE TITLE
printf crashes with NUL bytes, e.g. string `$'\U0'`

### ISSUE THREAD

**Issue by pdebelak** [oilshell/oil#1257]
I was trying to print out unicode characters with `printf` and accidentally passed a zero as a code. This caused a crash. This to affect other builtins (at least `test`):

```
oil$ printf $'\U41\n'
A
oil$ printf $'\U0\n'
Traceback (most recent call last):
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 325, in _cpython_main_hook
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 298, in main
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 289, in AppBundleMain
  File "/home/andy/git/oilshell/oil/core/shell.py", line 641, in Main
  File "/home/andy/git/oilshell/oil/core/main_loop.py", line 288, in Interactive
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1652, in ExecuteAndCatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1482, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 738, in _Dispatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 564, in _RunSimpleCommand
  File "/home/andy/git/oilshell/oil/core/executor.py", line 240, in RunSimpleCommand
  File "/home/andy/git/oilshell/oil/core/executor.py", line 134, in RunBuiltin
  File "/home/andy/git/oilshell/oil/osh/builtin_printf.py", line 451, in Run
  File "/home/andy/git/oilshell/oil/osh/builtin_printf.py", line 147, in Parse
AssertionError
FATAL: couldn't import from app bundle '/Users/pdebelak/.local/bin/oil.ovm' (1)
Stripping the oil.ovm binary may cause this error.
See https://github.com/oilshell/oil/issues/47
```

Also:

```
oil$ test -d $'Documents'; echo $?
0
oil$ test -d $'\U0'; echo $?
Traceback (most recent call last):
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 325, in _cpython_main_hook
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 298, in main
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 289, in AppBundleMain
  File "/home/andy/git/oilshell/oil/core/shell.py", line 641, in Main
  File "/home/andy/git/oilshell/oil/core/main_loop.py", line 288, in Interactive
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1652, in ExecuteAndCatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1482, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1058, in _Dispatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1547, in _ExecuteList
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1482, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 746, in _Dispatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1482, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 738, in _Dispatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 564, in _RunSimpleCommand
  File "/home/andy/git/oilshell/oil/core/executor.py", line 240, in RunSimpleCommand
  File "/home/andy/git/oilshell/oil/core/executor.py", line 134, in RunBuiltin
  File "/home/andy/git/oilshell/oil/osh/builtin_bracket.py", line 266, in Run
  File "/home/andy/git/oilshell/oil/osh/sh_expr_eval.py", line 935, in EvalB
  File "/home/andy/git/oilshell/oil/osh/bool_stat.py", line 47, in DoUnaryOp
TypeError: stat() argument 1 must be encoded string without null bytes, not str
FATAL: couldn't import from app bundle '/Users/pdebelak/.local/bin/oil.ovm' (1)
Stripping the oil.ovm binary may cause this error.
See https://github.com/oilshell/oil/issues/47
```

Unrelated (and I assume end users shouldn't be seeing these tracebacks ideally), but isn't it weird that these tracebacks refer to filepaths presumably from your (Andy's) computer?

**Comment by andychu** [comment]
Oof, thanks for finding this!  I just fixed the `printf` problem -- it was caused by an input handling quirk with NUL bytes.

- The `stat()` issue relates to building on top of CPython -- we might want to patch it, but it will also naturally go away with `oil-native`.

- The backtrace issue also relates to the fact that we're building on top of CPython.  Python embeds a filename in the bytecode, and I'm not sure if there is a way to control it.

BTW I reproduced the printf bug in `oil-native` as well, and the fix makes it go away.

------

One thing I also noticed is that `echo $'\0'` in bash and zsh behave differently.

- bash prints just `\n`
  - however for `echo -e '\0'` it prints `\0 \n`
- zsh prints `\0 \n` for both

Oil is like zsh now ... but I don't think that was intentional ... Thinking about what to do here ...

**Comment by andychu** [comment]
I fixed the printf bug last week , and added spec tests for these bugs:

- #1273 

Interestingly, testing revealed a difference between Oil in Python and C++, which we have to fix.

Thanks for the report!  Let me know if you encounter anything else, including bad error messages

**Comment by andychu** [comment]
Released, thanks for testing Oil !  https://www.oilshell.org/blog/2022/08/release-0.12.4.html
