### ISSUE TITLE
Symbol type (evaluated to itself, e.g. for type expressions)

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#1277]
Should behave something like Python

```
>>> from typing import Dict
>>> Dict
typing.Dict


>>> Dict[int,int]
typing.Dict[int, int]
>>> 

```

How to create it?

```
const Dict = Symbol() 

# or

const Dict = Symbol('Dict')
```

Or a builtin can create it:

```
define-symbols Dict Str Int Optional Mutated
```

------

Hay

```
Func concat {
  param left (List[Str])
  param right (List[Str])
  returns result (List[Str])
}
```

-----

Is `%foo` a Symbol or a string?   It can be an auto-created symbol `Symbol('foo')`

Does `%foo == 'foo'` ?   Probably not

But `Dict == Dict`, yes

Identity is an interned strings?  Plus children?  Might relate to Hay tree as well

**Comment by andychu** [comment]
related

- #1112

**Comment by andychu** [comment]
Similar to Wolfram m-expressions: https://en.wikipedia.org/wiki/M-expression

I also wonder if we want `Func[Str, Str => Int, Int]`  -- I think the grammar can handle that

**Comment by andychu** [comment]
Hm you can also makes slices.

For `QTT[name: Str, age: Int]`  

Or does it need to be:

`QTT['name': Str, 'age': Int]`    ?





```
>>> Dict[int, int:int]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/typing.py", line 682, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.6/typing.py", line 1107, in __getitem__
    params = tuple(_type_check(p, msg) for p in params)
  File "/usr/lib/python3.6/typing.py", line 1107, in <genexpr>
    params = tuple(_type_check(p, msg) for p in params)
  File "/usr/lib/python3.6/typing.py", line 374, in _type_check
    raise TypeError(msg + " Got %.100r." % (arg,))
TypeError: Parameters to generic types must be types. Got slice(<class 'int'>, <class 'int'>, None).
>>> 

```

**Comment by andychu** [comment]
### Useful in Hay, but also proc param signatures

https://oilshell.zulipchat.com/#narrow/stream/325160-oil-discuss-public/topic/Proc.20Param.20Passing.20-.20Brainstorming

Although I guess those can be arbitary expressions that are unevaluated

So they don't even need to be symbol values?  Just expressions
