### ISSUE TITLE
Soil: publishing CI results with ssh is flaky

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#1324]
I keep getting this on sourcehut

```
renamed '408452.index.html' -> '/home/travis_admin/travis-ci.oilshell.org/srht-jobs/index.html'
kex_exchange_identification: Connection closed by remote host

Connection closed by 208.113.220.36 port 22
```

Should switch to HTTP probably

- #1038

**Comment by andychu** [comment]
Hit this flakiness.  I think it happens when 2 jobs have the same ID?



```
fluvanna github-jobs$ cat 2023-03-05__03-22-33.json 
{
  "images-tagged": "REPOSITORY   TAG       IMAGE ID   CREATED   SIZE", 
  "job-name": "dummy", 
  "commit-line": "Merge 54f847edc40f5ae175e4da902adb4432f3db10aa into 42bec5c7b4475809f8f1528647e926c51c3153cc", 
  "commit-date": "2023-03-05T03:22:11+00:00", 
  "JOB_URL": "https://github.com/oilshell/oil/actions/runs/4334151641", 
  "image-layers": "IMAGE          CREATED       CREATED BY                                      SIZE      COMMENT\n60cdb72502fc   4 days ago    CMD [\"sh\" \"-c\" \"echo 'hello from oilshell/so\u2026   0B        buildkit.dockerfile.v0\n<missing>      4 days ago    USER ufluvanna github-jobs$ 

```


```
 Listing remote .wwz
-rw-r--r-- 1 runner docker 76248 Mar  5 03:23 _tmp/listing.txt
Copying raw.html
soil-web: Rewriting github-jobs/index.html
Traceback (most recent call last):
  File "/home/travis_admin/soil-web/soil/web.py", line 417, in <module>
    main(sys.argv)
  File "/home/travis_admin/soil-web/soil/web.py", line 338, in main
    rows = list(ParseJobs(sys.stdin))
  File "/home/travis_admin/soil-web/soil/web.py", line 118, in ParseJobs
    meta = json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 7 column 272 (char 603)
Error: Process completed with exit code 1.

```
