### ISSUE TITLE
Trying to echo an array element causes `AssertionError: 10` with misleading message about stripping `oil.ovm` binary

### ISSUE THREAD

**Issue by metov** [oilshell/oil#1376]
When I run this script:
```sh
#!/usr/bin/env oil

var ar = ["foo", "bar"]

# This works
var x = ar[1]
echo $x

# This doesn't
echo ${ar[1]}
```

I expect the output to be:
```
bar
bar
```

However, instead I get:
```
bar
Traceback (most recent call last):
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 336, in _cpython_main_hook
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 309, in main
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 300, in AppBundleMain
  File "/home/andy/git/oilshell/oil/core/shell.py", line 675, in Main
  File "/home/andy/git/oilshell/oil/core/main_loop.py", line 338, in Batch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1657, in ExecuteAndCatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1487, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 743, in _Dispatch
  File "/home/andy/git/oilshell/oil/osh/word_eval.py", line 2114, in EvalWordSequence2
  File "/home/andy/git/oilshell/oil/osh/word_eval.py", line 2074, in SimpleEvalWordSequence2
  File "/home/andy/git/oilshell/oil/osh/word_eval.py", line 1698, in _EvalWordToParts
  File "/home/andy/git/oilshell/oil/osh/word_eval.py", line 1561, in _EvalWordPart
  File "/home/andy/git/oilshell/oil/osh/word_eval.py", line 1246, in _EvalBracedVarSub
  File "/home/andy/git/oilshell/oil/osh/word_eval.py", line 1127, in _EvalBracketOp
  File "/home/andy/git/oilshell/oil/osh/word_eval.py", line 1035, in _ArrayIndex
AssertionError: 10
FATAL: couldn't import from app bundle '/usr/bin/oil.ovm' (1)
Stripping the oil.ovm binary may cause this error.
See https://github.com/oilshell/oil/issues/47
```

Btw, I have no `/home/andy/git/oilshell/oil/osh/word_eval.py` -- I'm assuming these are paths baked in during the build.

The error message points to #47, but this is appears to be a red herring. From what I can tell, the true problem is a syntax error. Granted, `https://www.oilshell.org/release/latest/doc/idioms.html#get-values-from-arrays-and-dicts` already says not to use that syntax, but a clearer error message would be better for new oil users.

Incidentally, how do you echo a single array element? Do you *have* to create a temporary variable?

**Comment by andychu** [comment]
Hi @metov , thanks for trying it, and for the report

This is a known issue -- #1092 

The workaround for now is the "Oil style" -- `$[a[0]]`, not bash style `${a[0]}`

There is a fundamental issue #636 which I hope can clean this up

**Comment by andychu** [comment]
For some background:

- `$[]` is a new Oil feature -- expression substitution -- substitution of Oil's Python-like expressions, and data types
- `${}` is compatible with bash, but it doesn't work with Oil data types now (and it shouldn't crash!)

**Comment by metov** [comment]
Thanks Andy! I tried
```
#!/usr/bin/env oil

var ar = ["foo", "bar"]

# This works
var x = ar[1]
echo $x

# This also works
echo $[ar[1]]
```
and it does indeed work.

I thought that it was probably a duplicate bug, but when I searched for the error online nothing relevant came up. So I made an issue with the error message in it to help future users. I'll close this issue since it's a duplicate of #1092.
