### ISSUE TITLE
crash when pyos.GetHomeDir() returns None

### ISSUE THREAD

**Issue by simonmichael** [oilshell/oil#1578]
I was using osh as usual, on mac. Then suddenly it stopped running, giving an error message like #47 and #1073:

```
/opt/homebrew/Cellar/oil/0.14.2/bin$ ls -l                                                                                                                                        
total 8528                                                                                                                                                                        
lrwxr-xr-x  1 502  admin        7 Mar  7 15:25 oil -> oil.ovm                                                                                                                     
-rwxr-xr-x  1 502  wheel  4365181 Apr 22 09:26 oil.ovm                                                                                                                            
lrwxr-xr-x  1 502  admin        7 Mar  7 15:25 osh -> oil.ovm                                                                                                                     
/opt/homebrew/Cellar/oil/0.14.2/bin$ objdump -t oil.ovm | wc -l                                                                                                                   
     209                                                                                                                                                                          
/opt/homebrew/Cellar/oil/0.14.2/bin$ ./osh                                                                                                                                        
Traceback (most recent call last):                                                                                                                                                
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 32, in _cpython_main_hook                                                                                                   
  File "/home/andy/git/oilshell/oil/bin/oils_for_unix.py", line 200, in main                                                                                                      
  File "/home/andy/git/oilshell/oil/bin/oils_for_unix.py", line 147, in AppBundleMain                                                                                             
  File "/home/andy/git/oilshell/oil/core/shell.py", line 548, in Main                                                                                                             
AssertionError                                                                                                                                                                    
FATAL: couldn't import from app bundle './osh' (1)                                                                                                                                
Stripping the oil.ovm binary may cause this error.                                                                                                                                
See https://github.com/oilshell/oil/issues/47                                                                                                                                     
```

I think the objdump command above is indicating that oil.ovm is stripped. I don't remember doing anything with brew. The only unusual thing I can think of is I killed the login daemon, closing all apps and forcing a new login (but not a system restart). After seeing the error I tried `brew reinstall oil` which didn't help. The brew formula doesn't seem to have been updated in the last month, or to have any relevant issues.

**Comment by simonmichael** [comment]
But happily, a full system restart fixed it! I think this can be closed.

**Comment by andychu** [comment]
Sorry for the delay -- I think this is a bug, `getpwnam()` is failing to get the user's home directory for some reason, and then we crash

I will have to look at what other shells do

I believe they fall back to the `$HOME` env variable.  I'm not sure why `getpwnam()` is failing, but probably because `/etc/passwd` wasn't readable, or maybe there is some system daemon managing that file, etc.

Thanks for the report!  Keep them coming

**Comment by andychu** [comment]
Hm I looked at dash source code, and it doesn't appears to always look up `$HOME` when expanding `~`, and it only calls `getpwnam()` when expanding `~someuser`

`$HOME` is apparently supposed to be set by the login process


https://superuser.com/questions/271925/where-is-the-home-environment-variable-set

So it's probably safer for us to do the same thing

**Comment by andychu** [comment]
Released a few weeks ago - https://www.oilshell.org/blog/2023/06/release-0.16.0.html

Thanks again for testing!
