### ISSUE TITLE
Crash When Comparing Functions (and Other Values)

### ISSUE THREAD

**Issue by PossiblyAShrub** [oilshell/oil#1732]
This also happens with other values, ie `^[1] === ^[1]`.

Not sure if we want to define equality on these values, but we shouldn't crash.

### Traceback

```
$ bin/ysh -c '= str === str'
Traceback (most recent call last):
  File "/home/aolse/oils/oil/bin/oils_for_unix.py", line 208, in <module>
    sys.exit(main(sys.argv))
  File "/home/aolse/oils/oil/bin/oils_for_unix.py", line 183, in main
    return AppBundleMain(argv)
  File "/home/aolse/oils/oil/bin/oils_for_unix.py", line 138, in AppBundleMain
    return shell.Main('ysh', arg_r, environ, login_shell, loader, readline)
  File "/home/aolse/oils/oil/core/shell.py", line 1009, in Main
    cmd_flags=cmd_eval.IsMainProgram)
  File "/home/aolse/oils/oil/core/main_loop.py", line 353, in Batch
    is_return, is_fatal = cmd_ev.ExecuteAndCatch(node, cmd_flags=cmd_flags)
  File "/home/aolse/oils/oil/osh/cmd_eval.py", line 1859, in ExecuteAndCatch
    status = self._Execute(node)
  File "/home/aolse/oils/oil/osh/cmd_eval.py", line 1681, in _Execute
    status = self._Dispatch(node, cmd_st)
  File "/home/aolse/oils/oil/osh/cmd_eval.py", line 1084, in _Dispatch
    val = self.expr_ev.EvalExpr(node.e, loc.Missing)
  File "/home/aolse/oils/oil/ysh/expr_eval.py", line 303, in EvalExpr
    val = self._EvalExpr(node)
  File "/home/aolse/oils/oil/ysh/expr_eval.py", line 1024, in _EvalExpr
    return self._EvalCompare(node)
  File "/home/aolse/oils/oil/ysh/expr_eval.py", line 573, in _EvalCompare
    result = val_ops.ExactlyEqual(left, right)
  File "/home/aolse/oils/oil/ysh/val_ops.py", line 410, in ExactlyEqual
    raise NotImplementedError(left)
NotImplementedError: (value.Func callable:<library.func_misc.Str_ object at 0x7fd2f31dfd90>)
```

**Comment by PossiblyAShrub** [comment]
Dumping part of the discussion on this on Zulip (https://oilshell.zulipchat.com/#narrow/stream/121539-oil-dev):

We should be raising a `TypeError`, and then use `is` for object identity (comparing object addresses, and objects may be mutable).

Right now we have === unimplemented for these types:

- Eggex
- Expr
- Template (not sure if this has been implemented)
- Block
- Func
- BoundFunc
- Proc
- Slice
- Range

Maybe `Slice` and `Range` would make sense to compare by value, but it's the "1-way vs. 2-way door problem." Even though it may make sense, there isn't a huge amount of application for this that we can come up with right now. So it's better to make it a `TypeError` so that we can implement/change this later.

**Comment by andychu** [comment]
It seems like we resolved the design discussion here?  So it could be just changing NotImplementedError to `raise error.TypeErr` ?  and adding a spec test

Good catch on this

(going through github issues now, sorry I have been focused on Zulip lately)

**Comment by PossiblyAShrub** [comment]
> It seems like we resolved the design discussion here? So it could be just changing NotImplementedError to `raise error.TypeErr` ?

Yes, I believe so. I can send over a PR with this.

**Comment by PossiblyAShrub** [comment]
I added the `pending-release` tag because #1754 has been merged. Let me know if this is not what should be done.

**Comment by andychu** [comment]
Fixed awhile ago, late announcement - https://www.oilshell.org/blog/2024/01/release-0.19.0.html
