### ISSUE TITLE
Can't serialize type List_ to JSON

### ISSUE THREAD

**Issue by rprtr258** [oilshell/oil#1773]
```
json write (list)
```

panics and gives traceback

```
$ ysh
ysh ysh-0.19.0$ json write (list)
Traceback (most recent call last):
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 34, in _cpython_main_hook
  File "/home/andy/git/oilshell/oil/bin/oils_for_unix.py", line 170, in main
  File "/home/andy/git/oilshell/oil/bin/oils_for_unix.py", line 137, in AppBundleMain
  File "/home/andy/git/oilshell/oil/core/shell.py", line 1026, in Main
  File "/home/andy/git/oilshell/oil/core/main_loop.py", line 311, in Interactive
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1929, in ExecuteAndCatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1810, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1528, in _Dispatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 896, in _DoSimple
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 590, in _RunSimpleCommand
  File "/home/andy/git/oilshell/oil/core/executor.py", line 295, in RunSimpleCommand
  File "/home/andy/git/oilshell/oil/core/executor.py", line 195, in RunBuiltin
  File "/home/andy/git/oilshell/oil/builtin/json_ysh.py", line 106, in Run
TypeError: Can't serialize type List_ to JSON
FATAL: couldn't import from app bundle '/usr/local/bin/oil.ovm' (1)
Stripping the oil.ovm binary may cause this error.
See https://github.com/oilshell/oil/issues/47
```

**Comment by andychu** [comment]
Great report, thank you!   This is due JSON being implemented with dynamic typing [1] -- I'm working on removing it right now!

I'll close this issue when it's fixed

[1] https://lobste.rs/s/hbzhdu/oils_0_18_0_progress_on_all_fronts

**Comment by andychu** [comment]
This is now fixed, will be out with the next release

```
$ bin/ysh -c 'json write (list)'
[ -c flag ]:1: json write: Can't serialize object of type BuiltinFunc
  json write (list)
  ^~~~
[ -c flag ]:1: errexit PID 645876: command.Simple failed with status 1
```

Thanks for the report!

**Comment by andychu** [comment]
Released, thanks for testing and contributing!   https://www.oilshell.org/blog/2024/02/release-0.20.0.html
