### ISSUE TITLE
ysh-0.20.0$ echo b'byte \xff' #=> Traceback

### ISSUE THREAD

**Issue by bar-g** [oilshell/oil#1826]
1. ysh-tour says not to use \xff, but without providing any reason.
2. FATAL error:

```
ysh ysh-0.20.0$ echo b'byte \xff' 

Traceback (most recent call last):
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 34, in _cpython_main_hook
  File "/home/andy/git/oilshell/oil/bin/oils_for_unix.py", line 170, in main
  File "/home/andy/git/oilshell/oil/bin/oils_for_unix.py", line 137, in AppBundleMain
  File "/home/andy/git/oilshell/oil/core/shell.py", line 1033, in Main
  File "/home/andy/git/oilshell/oil/core/main_loop.py", line 219, in Interactive
  File "/home/andy/git/oilshell/oil/osh/cmd_parse.py", line 2643, in ParseInteractiveLine
  File "/home/andy/git/oilshell/oil/osh/cmd_parse.py", line 2488, in _ParseCommandLine
  File "/home/andy/git/oilshell/oil/osh/cmd_parse.py", line 2412, in ParseAndOr
  File "/home/andy/git/oilshell/oil/osh/cmd_parse.py", line 2423, in _ParseAndOr
  File "/home/andy/git/oilshell/oil/osh/cmd_parse.py", line 2369, in ParsePipeline
  File "/home/andy/git/oilshell/oil/osh/cmd_parse.py", line 2345, in ParseCommand
  File "/home/andy/git/oilshell/oil/osh/cmd_parse.py", line 1108, in ParseSimpleCommand
  File "/home/andy/git/oilshell/oil/osh/cmd_parse.py", line 806, in _ScanSimpleCommand
  File "/home/andy/git/oilshell/oil/osh/cmd_parse.py", line 626, in _GetWord
  File "/home/andy/git/oilshell/oil/osh/word_parse.py", line 2067, in ReadWord
  File "/home/andy/git/oilshell/oil/osh/word_parse.py", line 1993, in _ReadWord
  File "/home/andy/git/oilshell/oil/osh/word_parse.py", line 763, in _ReadYshSingleQuoted
  File "/home/andy/git/oilshell/oil/osh/word_parse.py", line 617, in _ReadSingleQuoted
  File "/home/andy/git/oilshell/oil/osh/word_parse.py", line 720, in ReadSingleQuoted
AssertionError: (Token
  id: Id.Unknown_Tok
  col: 12
  length: 1
  span_id: 167
  line: (SourceLine line_num:24 content:"echo b'byte \\xff'\n" src:(source__Interactive))
  tval: "\\"
)
FATAL: couldn't import from app bundle '/usr/local/bin/oil.ovm' (1)
Stripping the oil.ovm binary may cause this error.
See https://github.com/oilshell/oil/issues/47
$
```

**Comment by andychu** [comment]
Oh good catch!  I will fix this

**Comment by andychu** [comment]
Fixed, will be out with next release

Thank you for testing!

**Comment by andychu** [comment]
Released!  https://www.oilshell.org/blog/2024/03/release-0.21.0.html
