### ISSUE TITLE
setvar a = u'\0'  => AssertionError

### ISSUE THREAD

**Issue by bar-g** [oilshell/oil#1851]
(error also with echo)
```
ysh ysh-0.20.0$ setvar a = u'\0'
Traceback (most recent call last):
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 34, in _cpython_main_hook
  File "/home/andy/git/oilshell/oil/bin/oils_for_unix.py", line 170, in main
  File "/home/andy/git/oilshell/oil/bin/oils_for_unix.py", line 137, in AppBundleMain
  File "/home/andy/git/oilshell/oil/core/shell.py", line 1033, in Main
  File "/home/andy/git/oilshell/oil/core/main_loop.py", line 219, in Interactive
  File "/home/andy/git/oilshell/oil/osh/cmd_parse.py", line 2643, in ParseInteractiveLine
  File "/home/andy/git/oilshell/oil/osh/cmd_parse.py", line 2488, in _ParseCommandLine
  File "/home/andy/git/oilshell/oil/osh/cmd_parse.py", line 2412, in ParseAndOr
  File "/home/andy/git/oilshell/oil/osh/cmd_parse.py", line 2423, in _ParseAndOr
  File "/home/andy/git/oilshell/oil/osh/cmd_parse.py", line 2369, in ParsePipeline
  File "/home/andy/git/oilshell/oil/osh/cmd_parse.py", line 2270, in ParseCommand
  File "/home/andy/git/oilshell/oil/osh/word_parse.py", line 1181, in ParseMutation
  File "/home/andy/git/oilshell/oil/frontend/parse_lib.py", line 324, in ParseMutation
  File "/home/andy/git/oilshell/oil/ysh/expr_parse.py", line 349, in Parse
  File "/home/andy/git/oilshell/oil/ysh/expr_parse.py", line 326, in _PushOilTokens
  File "/home/andy/git/oilshell/oil/osh/word_parse.py", line 720, in ReadSingleQuoted
AssertionError: (Token
  id: Id.Unknown_Tok
  col: 13
  length: 1
  span_id: 11
  line: (SourceLine line_num:1 content:"setvar a = u'\\0'\n" src:(source__Interactive))
  tval: "\\"
)
FATAL: couldn't import from app bundle '/usr/local/bin/oil.ovm' (1)
Stripping the oil.ovm binary may cause this error.
See https://github.com/oilshell/oil/issues/47
```

**Comment by andychu** [comment]
I just tried this at HEAD, it works

I fixed #1826 yesterday, this is the same thing I believe

You can test the new code by

1. Grabbing a new tarball from the CI - http://travis-ci.oilshell.org/github-jobs/ - jobs `ovm-tarball` or `cpp-tarball` have tarball links
2. Building the git repo - https://github.com/oilshell/oil/wiki/Contributing
