### ISSUE TITLE
[ BUG ] `build/deps.sh install-wedges-fast` failing on a newly cloned repo

### ISSUE THREAD

**Issue by glyh** [oilshell/oil#1931]
```
build/deps.sh: 
build/deps.sh: === Installing wedges with 12 jobs in parallel
build/deps.sh: 
  TASK  13:08:51  python2 2.7.18 > _build/wedge/logs/python2.log.txt
  TASK  13:08:51  pyflakes 2.4.0 > _build/wedge/logs/pyflakes.log.txt
  TASK  13:08:51  python3 3.10.4 > _build/wedge/logs/python3.log.txt
  TASK  13:08:51  cmark 0.29.0 > _build/wedge/logs/cmark.log.txt
  TASK  13:08:51  mypy 0.780 > _build/wedge/logs/mypy.log.txt
  TASK  13:08:51  re2c 3.0 > _build/wedge/logs/re2c.log.txt
  TASK  13:08:51  bash 4.4 > _build/wedge/logs/bash.log.txt
  TASK  13:08:51  dash 0.5.10.2 > _build/wedge/logs/dash.log.txt
  TASK  13:08:51  mksh R52c > _build/wedge/logs/mksh.log.txt
  TASK  13:08:51  busybox 1.35.0 > _build/wedge/logs/busybox.log.txt
  TASK  13:08:51  zsh 5.1.1 > _build/wedge/logs/zsh.log.txt
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/lyh/Documents/CS/oils/oil/benchmarks/time_.py", line 61, in <module>
  File "/home/lyh/Documents/CS/oils/oil/benchmarks/time_.py", line 61, in <module>
    raise AssertionError('time-helper not found')
    raise AssertionError('time-helper not found')
AssertionError: time-helper not found
AssertionError: time-helper not found
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/lyh/Documents/CS/oils/oil/benchmarks/time_.py", line 61, in <module>
  File "/home/lyh/Documents/CS/oils/oil/benchmarks/time_.py", line 61, in <module>
Traceback (most recent call last):
  File "/home/lyh/Documents/CS/oils/oil/benchmarks/time_.py", line 61, in <module>
    raise AssertionError('time-helper not found')
    raise AssertionError('time-helper not found')
AssertionError: time-helper not found
AssertionError: time-helper not found
    raise AssertionError('time-helper not found')
AssertionError: time-helper not found
Traceback (most recent call last):
  File "/home/lyh/Documents/CS/oils/oil/benchmarks/time_.py", line 61, in <module>
    raise AssertionError('time-helper not found')
AssertionError: time-helper not found
Traceback (most recent call last):
  File "/home/lyh/Documents/CS/oils/oil/benchmarks/time_.py", line 61, in <module>
    raise AssertionError('time-helper not found')
AssertionError: time-helper not found
Traceback (most recent call last):
  File "/home/lyh/Documents/CS/oils/oil/benchmarks/time_.py", line 61, in <module>
    raise AssertionError('time-helper not found')
AssertionError: time-helper not found
Traceback (most recent call last):
  File "/home/lyh/Documents/CS/oils/oil/benchmarks/time_.py", line 61, in <module>
    raise AssertionError('time-helper not found')
AssertionError: time-helper not found
Traceback (most recent call last):
  File "/home/lyh/Documents/CS/oils/oil/benchmarks/time_.py", line 61, in <module>
    raise AssertionError('time-helper not found')
AssertionError: time-helper not found
Traceback (most recent call last):
  File "/home/lyh/Documents/CS/oils/oil/benchmarks/time_.py", line 61, in <module>
    raise AssertionError('time-helper not found')
AssertionError: time-helper not found

```

**Comment by andychu** [comment]
OK yes, I left off in the middle of this

We have a serial and parallel version

I never switched to the parallel version -- I wanted to switch to `~/wedge` over `/wedge` first

---

I guess we need to build time-helper first, before fetching -- thanks for the feedback
