### ISSUE TITLE
Gracefully reject unhandled $PS1 escape codes

### ISSUE THREAD

**Issue by BatmanAoD** [oilshell/oil#214]
I have `\W` in my Bash PS1, which isn't handled by Osh yet. So I was not able to run `osh` at all, and didn't realize at first that my PS1 was the problem.

Here's the exception that was printed:

```
LTUSFTCKQ6T|oil> bin/osh
Traceback (most recent call last):
  File "/home/kjstrand/personal-projects/oil/bin/oil.py", line 571, in <module>
    main(sys.argv)
  File "/home/kjstrand/personal-projects/oil/bin/oil.py", line 544, in main
    sys.exit(AppBundleMain(argv))
  File "/home/kjstrand/personal-projects/oil/bin/oil.py", line 518, in AppBundleMain
    status = ShellMain('osh', argv0, main_argv, login_shell)
  File "/home/kjstrand/personal-projects/oil/bin/oil.py", line 293, in ShellMain
    line_reader = reader.InteractiveLineReader(arena, prompt)
  File "/home/kjstrand/personal-projects/oil/frontend/reader.py", line 48, in __init__
    self.Reset()  # initialize self.prompt_str
  File "/home/kjstrand/personal-projects/oil/frontend/reader.py", line 67, in Reset
    self.prompt_str = self.prompt.FirstPrompt()
  File "/home/kjstrand/personal-projects/oil/core/ui.py", line 269, in FirstPrompt
    return self.EvalPrompt(val)
  File "/home/kjstrand/personal-projects/oil/core/ui.py", line 240, in EvalPrompt
    ps1_str = self._ReplaceBackslashCodes(tokens)
  File "/home/kjstrand/personal-projects/oil/core/ui.py", line 217, in _ReplaceBackslashCodes
    raise NotImplementedError(char)
NotImplementedError: W
```

I'll submit a PR with a suggestion momentarily.

**Comment by andychu** [comment]
Thanks for the report, I appreciate it!

I fixed this a different way because of the double-print issue you mentioned.  That is because Reset() is called twice, which is probably a minor mistake, but that area has some churn now so it's not worth changing.

A pull request to implement `\W` would be very much appreciated :)
