### ISSUE TITLE
test -s not implemented (`shopt -s histappend` causes osh to exit)

### ISSUE THREAD

**Issue by okayzed** [oilshell/oil#218]
when sourcing my .bashrc, i get the following error and osh exits early. likely because i use histappend

the shopt line is: `shopt -s histappend`

```
osh 'shopt' usage error: Invalid option 'histappend'
Traceback (most recent call last):
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 563, in _cpython_main_hook
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 545, in main
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 519, in AppBundleMain
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 330, in ShellMain
  File "/home/andy/git/oilshell/oil/core/main_loop.py", line 71, in Interactive
  File "/home/andy/git/oilshell/oil/osh/cmd_exec.py", line 1207, in ExecuteAndCatch
  File "/home/andy/git/oilshell/oil/osh/cmd_exec.py", line 1155, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_exec.py", line 1100, in _Dispatch
  File "/home/andy/git/oilshell/oil/osh/cmd_exec.py", line 577, in _RunSimpleCommand
  File "/home/andy/git/oilshell/oil/osh/cmd_exec.py", line 318, in _RunBuiltin
  File "/home/andy/git/oilshell/oil/osh/cmd_exec.py", line 237, in _Source
  File "/home/andy/git/oilshell/oil/osh/cmd_exec.py", line 169, in _EvalHelper
  File "/home/andy/git/oilshell/oil/core/main_loop.py", line 124, in Batch
  File "/home/andy/git/oilshell/oil/osh/cmd_exec.py", line 1207, in ExecuteAndCatch
  File "/home/andy/git/oilshell/oil/osh/cmd_exec.py", line 1155, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_exec.py", line 934, in _Dispatch
  File "/home/andy/git/oilshell/oil/osh/cmd_exec.py", line 1155, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_exec.py", line 1100, in _Dispatch
  File "/home/andy/git/oilshell/oil/osh/cmd_exec.py", line 577, in _RunSimpleCommand
  File "/home/andy/git/oilshell/oil/osh/cmd_exec.py", line 351, in _RunBuiltin
  File "/home/andy/git/oilshell/oil/osh/builtin_bracket.py", line 191, in Test
  File "/home/andy/git/oilshell/oil/osh/expr_eval.py", line 644, in Eval
NotImplementedError: BoolUnary_s
FATAL: couldn't import from app bundle './bin/oil.ovm' (1)
Stripping the oil.ovm binary may cause this error.
See https://github.com/oilshell/oil/issues/47
```

**Comment by okayzed** [comment]
thanks for fixing
