### ISSUE TITLE
Stack trace when hitting Ctrl-C in command sub

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#239]
This command hangs, and then hitting Ctrl-C will cause this exception.

Will this change if we enable KeyboardInterrupt?

Note: `cat` doesn't do the same thing -- it's specific to command subs.

```
[osh] lisa /home/andy/git/oilshell/oil$ echo `grep NOTES.txt`
^CTraceback (most recent call last):
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 762, in <module>
    main(sys.argv)
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 731, in main
    sys.exit(AppBundleMain(argv))
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 705, in AppBundleMain
    status = ShellMain('osh', argv0, main_argv, login_shell)
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 514, in ShellMain
    return main_loop.Interactive(opts, ex, c_parser, display, arena)
  File "/home/andy/git/oilshell/oil/core/main_loop.py", line 71, in Interactive
    is_control_flow, is_fatal = ex.ExecuteAndCatch(node)
  File "/home/andy/git/oilshell/oil/osh/cmd_exec.py", line 1241, in ExecuteAndCatch
    status = self._Execute(node, fork_external=fork_external)
  File "/home/andy/git/oilshell/oil/osh/cmd_exec.py", line 1189, in _Execute
    status, check_errexit = self._Dispatch(node, fork_external)
  File "/home/andy/git/oilshell/oil/osh/cmd_exec.py", line 718, in _Dispatch
    argv = self.word_ev.EvalWordSequence(words)
  File "/home/andy/git/oilshell/oil/osh/word_eval.py", line 1123, in EvalWordSequence
    return self._EvalWordSequence(words)
  File "/home/andy/git/oilshell/oil/osh/word_eval.py", line 1096, in _EvalWordSequence
    self._EvalWordToParts(w, False, part_vals)  # not double quoted
  File "/home/andy/git/oilshell/oil/osh/word_eval.py", line 897, in _EvalWordToParts
    self._EvalWordPart(p, part_vals, quoted=quoted)
  File "/home/andy/git/oilshell/oil/osh/word_eval.py", line 830, in _EvalWordPart
    v = self._EvalCommandSub(part.command_list, quoted)
  File "/home/andy/git/oilshell/oil/osh/word_eval.py", line 1133, in _EvalCommandSub
    stdout = self.ex.RunCommandSub(node)
  File "/home/andy/git/oilshell/oil/osh/cmd_exec.py", line 1304, in RunCommandSub
    byte_str = posix.read(r, 4096)
OSError: [Errno 4] Interrupted system call

```

**Comment by andychu** [comment]
Fixed with http://www.oilshell.org/release/0.6.pre16/
