### ISSUE TITLE
cd fails when called without a parameter

### ISSUE THREAD

**Issue by lheckemann** [oilshell/oil#24]
```
$ ./_bin/oil.ovm osh
osh$ cd
Traceback (most recent call last):
  File "/home/andy/git/oil/Python-2.7.13/Lib/runpy.py", line 174, in _run_module_as_main
  File "/home/andy/git/oil/Python-2.7.13/Lib/runpy.py", line 72, in _run_code
  File "/home/andy/git/oil/bin/oil.py", line 440, in <module>
  File "/home/andy/git/oil/bin/oil.py", line 427, in main
  File "/home/andy/git/oil/bin/oil.py", line 410, in OilMain
  File "/home/andy/git/oil/bin/oil.py", line 311, in OshMain
  File "/home/andy/git/oil/bin/oil.py", line 122, in InteractiveLoop
  File "/home/andy/git/oil/bin/../core/cmd_exec.py", line 892, in Execute
  File "/home/andy/git/oil/bin/../core/cmd_exec.py", line 856, in _Execute
  File "/home/andy/git/oil/bin/../core/cmd_exec.py", line 674, in _Dispatch
  File "/home/andy/git/oil/bin/../core/cmd_exec.py", line 885, in _ExecuteList
  File "/home/andy/git/oil/bin/../core/cmd_exec.py", line 856, in _Execute
  File "/home/andy/git/oil/bin/../core/cmd_exec.py", line 584, in _Dispatch
  File "/home/andy/git/oil/bin/../core/cmd_exec.py", line 473, in _RunSimpleCommand
  File "/home/andy/git/oil/bin/../core/cmd_exec.py", line 214, in _RunBuiltin
  File "/home/andy/git/oil/bin/../core/builtin.py", line 406, in _Cd
IndexError: list index out of range
```

**Comment by andychu** [comment]
should use $HOME

**Comment by andychu** [comment]
Thanks for noticing the bug, fixed!
