### ISSUE TITLE
Regression in 60665f24

### ISSUE THREAD

**Issue by jyn514** [oilshell/oil#270]
Starting in https://github.com/oilshell/oil/commit/60665f242b11bec29bd9d9ef228ecc2ef950f4fd, resizing the terminal causes OSH to crash.

```
$ Traceback (most recent call last):
  File "/home/joshua/Documents/Programming/unchanged/oil/bin/oil.py", line 783, in <module>
    main(sys.argv)
  File "/home/joshua/Documents/Programming/unchanged/oil/bin/oil.py", line 752, in main
    sys.exit(AppBundleMain(argv))
  File "/home/joshua/Documents/Programming/unchanged/oil/bin/oil.py", line 726, in AppBundleMain
    status = ShellMain('osh', argv0, main_argv, login_shell)
  File "/home/joshua/Documents/Programming/unchanged/oil/bin/oil.py", line 535, in ShellMain
    return main_loop.Interactive(opts, ex, c_parser, display, arena)
  File "/home/joshua/Documents/Programming/unchanged/oil/core/main_loop.py", line 47, in Interactive
    w = c_parser.Peek()  # may raise HistoryError or ParseError
  File "/home/joshua/Documents/Programming/unchanged/oil/osh/cmd_parse.py", line 453, in Peek
    self._Peek()
  File "/home/joshua/Documents/Programming/unchanged/oil/osh/cmd_parse.py", line 464, in _Peek
    w = self.w_parser.ReadWord(self.next_lex_mode)
  File "/home/joshua/Documents/Programming/unchanged/oil/osh/word_parse.py", line 1190, in ReadWord
    w, need_more = self._ReadWord(lex_mode)
  File "/home/joshua/Documents/Programming/unchanged/oil/osh/word_parse.py", line 1105, in _ReadWord
    self._Peek()
  File "/home/joshua/Documents/Programming/unchanged/oil/osh/word_parse.py", line 119, in _Peek
    self.cur_token = self.lexer.Read(self.next_lex_mode)
  File "/home/joshua/Documents/Programming/unchanged/oil/frontend/lexer.py", line 256, in Read
    t = self._Read(lex_mode)
  File "/home/joshua/Documents/Programming/unchanged/oil/frontend/lexer.py", line 225, in _Read
    line_id, line, line_pos = self.line_reader.GetLine()
  File "/home/joshua/Documents/Programming/unchanged/oil/frontend/reader.py", line 32, in GetLine
    line = self._GetLine()
  File "/home/joshua/Documents/Programming/unchanged/oil/frontend/reader.py", line 78, in _GetLine
    line = raw_input(self.prompt_str) + '\n'  # newline required
  File "/home/joshua/Documents/Programming/unchanged/oil/bin/oil.py", line 529, in <lambda>
    signal.signal(signal.SIGWINCH, lambda x, y: display.OnWindowChange())
  File "/home/joshua/Documents/Programming/unchanged/oil/core/comp_ui.py", line 452, in OnWindowChange
    self.readline_mod.resize_terminal()
AttributeError: 'module' object has no attribute 'resize_terminal'
```

**Comment by jyn514** [comment]
For what it's worth, readline seems to behave in the commit before this, I can change the width of my terminal and the line will still wrap properly.

**Comment by andychu** [comment]
I'm pretty sure I fixed this with

https://github.com/oilshell/oil/commit/952e96e03867eeb19814d775ea8fa135c6ef60e7

and the master branch should be fixed?  One issue you might run into is stale builds after a git pull, so I do

   make clean-repo

And then `make` again or `make _bin/oil.ovm-dbg`, etc.

(FWIW there is a rather complicated process of "hollowing out the Python interpreter", so whenever we use new C methods, the list in `build/oil-defs/` has to be updated.  I hope to drastically simplify this at some point, and also fix the stale build problem.)

**Comment by andychu** [comment]
To clarify, C code can be stale (`_bin/osh` running `_bin/oil.ovm*`), but the normal case of  running `bin/osh` should never be steale.

- `bin/osh` is running a normal Python interpreter with normal dynamically Python C extensions.
- `_bin/osh` is a symlink to `_bin/oil.ovm`, which is our stripped down Python interpreter, which relies on the `build/oil-defs/` list.

**Comment by jyn514** [comment]
This is with `bin/osh`, not any C code.

**Comment by jyn514** [comment]
running `build/dev.sh minimal` seems to have fixed it.
