### ISSUE TITLE
Degenerate case: what if user is deleted while running?

### ISSUE THREAD

**Issue by jyn514** [oilshell/oil#278]
This is a very silly issue and you can close it if you like, I'm aware this is ridiculous.

What if the user is deleted while logged in? Their home directory will be removed from `/etc/passwd`, causing `osh` to throw an assertion error at startup:

```
Traceback (most recent call last):
  File "/usr/local/src/oil/bin/oil.py", line 779, in <module>
    main(sys.argv)
  File "/usr/local/src/oil/bin/oil.py", line 748, in main
    sys.exit(AppBundleMain(argv))
  File "/usr/local/src/oil/bin/oil.py", line 722, in AppBundleMain
    status = ShellMain('osh', argv0, main_argv, login_shell)
  File "/usr/local/src/oil/bin/oil.py", line 440, in ShellMain
    assert home_dir is not None
AssertionError
```

bash instead shows a warning and continues:

```
osh$ bash
groups: cannot find name for group ID 1002
I have no name!@joshua-ThinkPad:/usr/local/src/oil$
```

Steps to reproduce:
1. Create a user (don't try this with your main account!!): `sudo adduser temp`
2. Log in as that user: `su temp`
3. In another terminal, remove that user: `sudo userdel -f temp`. You need the -f because userdel knows this is a really bad idea since you're logged in the other terminal.
4. Run `bin/osh` as that user.

**Comment by andychu** [comment]
Thanks for the repro and comparison with bash.  Yes OSH should be robust against this kind of thing.  I think I fixed a bug when the current directory disappears, which is pretty common in practice.  I'm not sure how often this will occur but the AssertionError isn't right.

**Comment by jyn514** [comment]
It's fixed when the directory disappears, but not when it doesn't exist at startup:

```
(osh) $ mkdir tmp
$ cd tmp
$ rmdir ../tmp
$ ls
ls: cannot open directory '.': No such file or directory
$ ../bin/osh
sh: 0: getcwd() failed: No such file or directory
Traceback (most recent call last):
  File "/home/joshua/Documents/Programming/unchanged/oil/bin/oil.py", line 779, in <module>
    main(sys.argv)
  File "/home/joshua/Documents/Programming/unchanged/oil/bin/oil.py", line 748, in main
    sys.exit(AppBundleMain(argv))
  File "/home/joshua/Documents/Programming/unchanged/oil/bin/oil.py", line 722, in AppBundleMain
    status = ShellMain('osh', argv0, main_argv, login_shell)
  File "/home/joshua/Documents/Programming/unchanged/oil/bin/oil.py", line 291, in ShellMain
    has_main=has_main)
  File "/home/joshua/Documents/Programming/unchanged/oil/osh/state.py", line 469, in __init__
    self._InitDefaults()
  File "/home/joshua/Documents/Programming/unchanged/oil/osh/state.py", line 515, in _InitDefaults
    ExportGlobalString(self, 'PWD', posix.getcwd())
OSError: [Errno 2] No such file or directory
```
