### ISSUE TITLE
corner case: file limit

### ISSUE THREAD

**Issue by jyn514** [oilshell/oil#285]
If we run out of file descriptors, osh crashes.

```
$ ulimit -n 15
$ bin/osh
$ ls | ls | ls | ls | ls
osh I/O error: Too many open files                                                           
Traceback (most recent call last):                                                           
  File "/usr/local/src/oil/bin/oil.py", line 778, in <module>                                
    main(sys.argv)                                                                           
  File "/usr/local/src/oil/bin/oil.py", line 747, in main                                    
    sys.exit(AppBundleMain(argv))                                                            
  File "/usr/local/src/oil/bin/oil.py", line 721, in AppBundleMain                           
    status = ShellMain('osh', argv0, main_argv, login_shell)
  File "/usr/local/src/oil/bin/oil.py", line 534, in ShellMain
    return main_loop.Interactive(opts, ex, c_parser, display, arena)
  File "/usr/local/src/oil/core/main_loop.py", line 102, in Interactive
    c_parser.ResetInputObjects()
  File "/usr/local/src/oil/osh/cmd_parse.py", line 436, in ResetInputObjects
    self.line_reader.Reset()
  File "/usr/local/src/oil/frontend/reader.py", line 110, in Reset
    self.prompt_str = self.prompt_ev.FirstPromptEvaluator()
  File "/usr/local/src/oil/osh/prompt.py", line 209, in FirstPromptEvaluator
    return self.EvalPrompt(val)
  File "/usr/local/src/oil/osh/prompt.py", line 203, in EvalPrompt
    val2 = self.ex.word_ev.EvalForPlugin(ps1_word)
  File "/usr/local/src/oil/osh/word_eval.py", line 970, in EvalForPlugin
    val = self.EvalWordToString(w)
  File "/usr/local/src/oil/osh/word_eval.py", line 928, in EvalWordToString
    self._EvalWordPart(p, part_vals, quoted=False)
  File "/usr/local/src/oil/osh/word_eval.py", line 821, in _EvalWordPart
    v = self._EvalCommandSub(part.command_list, quoted)
  File "/usr/local/src/oil/osh/word_eval.py", line 1139, in _EvalCommandSub
    stdout = self.ex.RunCommandSub(node)
  File "/usr/local/src/oil/osh/cmd_exec.py", line 1272, in RunCommandSub
    r, w = posix.pipe()
OSError: [Errno 24] Too many open files
```

**Comment by andychu** [comment]
Thanks, I will fix this!  I think this will be solved by the same fix as the other `$PS1` issue you mentioned.

I put a big except statement in `ExecuteAndCatch()` but the prompt evaluation falls outside of that, so it needs one too.

**Comment by andychu** [comment]
OK I just fixed this.  The `demo/cannot-fork.sh` is useful for testing out what happens with other shells:

- bash goes into a non-responsive retry loop (at least on my machine)
- dash goes into a tight infinite loop
- mksh hangs non-responsively
- zsh doesn't respect command sub in PS1 so it doesn't apply

So OSH actually has the best behavior here!  It has `$PS1` evaluate to a string that contains a description of the error, and the shell is otherwise responsive.

I suspect this is because when you don't have exceptions, it's hard to handle all these corner cases.  It's tempting to leave out the error handling when you have to handle them all manually.

**Comment by jyn514** [comment]
Just tested, looks great! I was wondering why dash sometimes looped infinitely and sometimes worked fine, I guess `PS1` was the difference. Thanks for the hard work!

**Comment by andychu** [comment]
This fix is released!  Latest version of OSH: http://www.oilshell.org/release/0.6.pre20/
