### ISSUE TITLE
ValueError when evaluating environment variable

### ISSUE THREAD

**Issue by jyn514** [oilshell/oil#332]
```
(bash) /.../src/oil ▶️ PS1='> '
> bin/osh
osh$ echo $PS1
Traceback (most recent call last):
  File "/usr/local/src/oil/bin/oil.py", line 859, in <module>
    main(sys.argv)
  File "/usr/local/src/oil/bin/oil.py", line 827, in main
    sys.exit(AppBundleMain(argv))
  File "/usr/local/src/oil/bin/oil.py", line 797, in AppBundleMain
    status = ShellMain('osh', argv0, main_argv, login_shell)
  File "/usr/local/src/oil/bin/oil.py", line 602, in ShellMain
    return main_loop.Interactive(opts, ex, c_parser, display, errfmt)
  File "/usr/local/src/oil/core/main_loop.py", line 90, in Interactive
    is_control_flow, is_fatal = ex.ExecuteAndCatch(node)
  File "/usr/local/src/oil/osh/cmd_exec.py", line 1188, in ExecuteAndCatch
    status = self._Execute(node, fork_external=fork_external)
  File "/usr/local/src/oil/osh/cmd_exec.py", line 1136, in _Execute
    status, check_errexit = self._Dispatch(node, fork_external)
  File "/usr/local/src/oil/osh/cmd_exec.py", line 654, in _Dispatch
    arg_vec = self.word_ev.EvalWordSequence2(words)
  File "/usr/local/src/oil/osh/word_eval.py", line 1109, in EvalWordSequence2
    self._EvalWordToParts(w, False, part_vals)  # not double quoted
  File "/usr/local/src/oil/osh/word_eval.py", line 890, in _EvalWordToParts
    self._EvalWordPart(p, part_vals, quoted=quoted)
  File "/usr/local/src/oil/osh/word_eval.py", line 840, in _EvalWordPart
    var_num = int(part.token.val[1:])
ValueError: invalid literal for int() with base 10: 'PS1'
```

The same error seems to show up for a lot of other variables, I've tried `$PWD`, `$HOME`, and `$SOME_UNSET_VARIABLE`

**Comment by andychu** [comment]
Are you running the dev build or a release?  Maybe you need to do `build/dev.sh minimal` or `build/dev.sh all` ?

That said I did notice a problem with PS1, but I didn't get any ValueError.  Looking at it.

**Comment by jyn514** [comment]
Ok that was the issue, I had to run `build/dev.sh all`.

**Comment by andychu** [comment]
@jyn514 OK glad it works, I made a note at the end of

https://github.com/oilshell/oil/wiki/Contributing

If you notice any other friction, feel free to edit that page and/or bring it up on Zulip.
