### ISSUE TITLE
AssertionError on double quotes

### ISSUE THREAD

**Issue by jyn514** [oilshell/oil#333]
```
(bash) > bin/osh
osh$ ""
Traceback (most recent call last):
  File "/usr/local/src/oil/bin/oil.py", line 859, in <module>
    main(sys.argv)
  File "/usr/local/src/oil/bin/oil.py", line 827, in main
    sys.exit(AppBundleMain(argv))
  File "/usr/local/src/oil/bin/oil.py", line 797, in AppBundleMain
    status = ShellMain('osh', argv0, main_argv, login_shell)
  File "/usr/local/src/oil/bin/oil.py", line 602, in ShellMain
    return main_loop.Interactive(opts, ex, c_parser, display, errfmt)
  File "/usr/local/src/oil/core/main_loop.py", line 47, in Interactive
    result = c_parser.ParseInteractiveLine()
  File "/usr/local/src/oil/osh/cmd_parse.py", line 1837, in ParseInteractiveLine
    self._Peek()
  File "/usr/local/src/oil/osh/cmd_parse.py", line 451, in _Peek
    w = self.w_parser.ReadWord(self.next_lex_mode)
  File "/usr/local/src/oil/osh/word_parse.py", line 1231, in ReadWord
    w, need_more = self._ReadWord(lex_mode)
  File "/usr/local/src/oil/osh/word_parse.py", line 1188, in _ReadWord
    w = self._ReadCompoundWord(lex_mode=lex_mode)
  File "/usr/local/src/oil/osh/word_parse.py", line 1045, in _ReadCompoundWord
    part = self._ReadLeftParts()
  File "/usr/local/src/oil/osh/word_parse.py", line 544, in _ReadLeftParts
    return self._ReadDoubleQuotedPart()
  File "/usr/local/src/oil/osh/word_parse.py", line 685, in _ReadDoubleQuotedPart
    self._ReadLikeDQ(left_dq_token, dq_part.parts)
  File "/usr/local/src/oil/osh/word_parse.py", line 654, in _ReadLikeDQ
    assert self.token_type == Id.Right_DoubleQuote, (self, self.token_type)
AssertionError: (<osh.word_parse.WordParser object at 0x7fb19fb78150>, <Id_t Right_SingleQuote 84>)
```

I modified the code slightly, the original reads `assert self.token_type == Id.Right_DoubleQuote, self.token_type`. Not sure what's going on here, the lexer seems to have mistaken `"` for `'`?

**Comment by jyn514** [comment]
See https://github.com/oilshell/oil/issues/332
