### ISSUE TITLE
Crash when using $* with an empty IFS

### ISSUE THREAD

**Issue by lhoursquentin** [oilshell/oil#373]
Using `$*` when `IFS` is empty causes osh to crash. Unsetting IFS does not have this issue.

Test
```bash
$ bin/osh -c 'IFS=; echo "$*"'
```
Output
```
Traceback (most recent call last):
  File "/home/quentin/oil/bin/oil.py", line 859, in <module>
    main(sys.argv)
  File "/home/quentin/oil/bin/oil.py", line 827, in main
    sys.exit(AppBundleMain(argv))
  File "/home/quentin/oil/bin/oil.py", line 797, in AppBundleMain
    status = ShellMain('osh', argv0, main_argv, login_shell)
  File "/home/quentin/oil/bin/oil.py", line 610, in ShellMain
    status = main_loop.Batch(ex, c_parser, arena, nodes_out=nodes_out)
  File "/home/quentin/oil/core/main_loop.py", line 162, in Batch
    is_control_flow, is_fatal = ex.ExecuteAndCatch(node)
  File "/home/quentin/oil/osh/cmd_exec.py", line 1188, in ExecuteAndCatch
    status = self._Execute(node, fork_external=fork_external)
  File "/home/quentin/oil/osh/cmd_exec.py", line 1136, in _Execute
    status, check_errexit = self._Dispatch(node, fork_external)
  File "/home/quentin/oil/osh/cmd_exec.py", line 862, in _Dispatch
    status = self._ExecuteList(node.children)
  File "/home/quentin/oil/osh/cmd_exec.py", line 1157, in _ExecuteList
    status = self._Execute(child)  # last status wins
  File "/home/quentin/oil/osh/cmd_exec.py", line 1136, in _Execute
    status, check_errexit = self._Dispatch(node, fork_external)
  File "/home/quentin/oil/osh/cmd_exec.py", line 654, in _Dispatch
    arg_vec = self.word_ev.EvalWordSequence2(words)
  File "/home/quentin/oil/osh/word_eval.py", line 1109, in EvalWordSequence2
    self._EvalWordToParts(w, False, part_vals)  # not double quoted
  File "/home/quentin/oil/osh/word_eval.py", line 890, in _EvalWordToParts
    self._EvalWordPart(p, part_vals, quoted=quoted)
  File "/home/quentin/oil/osh/word_eval.py", line 818, in _EvalWordPart
    self._EvalDoubleQuotedPart(part, part_vals)
  File "/home/quentin/oil/osh/word_eval.py", line 466, in _EvalDoubleQuotedPart
    self._EvalWordPart(p, part_vals, quoted=True)
  File "/home/quentin/oil/osh/word_eval.py", line 848, in _EvalWordPart
    val = self._DecayArray(val)
  File "/home/quentin/oil/osh/word_eval.py", line 470, in _DecayArray
    sep = self.splitter.GetJoinChar()
  File "/home/quentin/oil/osh/split.py", line 139, in GetJoinChar
    return val.s[0]
IndexError: string index out of range
```

**Comment by andychu** [comment]
Released: http://www.oilshell.org/release/0.6.pre23/
