### ISSUE TITLE
[Regression] devtools/release.sh fails

### ISSUE THREAD

**Issue by jyn514** [oilshell/oil#420]
```
(osh) $ devtools/release.sh oil
{ echo '_build/release-date.txt release-date.txt'; \
  cat build/oil-manifest.txt \
      _build/oil/opy-app-deps.txt; \
  build/actions.sh quick-ref-manifest _devbuild/osh-quick-ref; \
  build/actions.sh pyc-version-manifest _build/oil/bytecode-opy-manifest.txt; \
} > _build/oil/bytecode-opy-manifest.txt
build/make_zip.py _build/oil/bytecode-opy.zip < _build/oil/bytecode-opy-manifest.txt
Traceback (most recent call last):
  File "build/make_zip.py", line 50, in <module>
    main(sys.argv)
  File "build/make_zip.py", line 42, in main
    z.write(full_path, rel_path)
  File "/usr/lib/python2.7/zipfile.py", line 1123, in write
    st = os.stat(filename)
OSError: [Errno 2] No such file or directory: '/home/joshua/Documents/Programming/oil/pylib/os_.py
build/oil.mk:62: recipe for target '_build/oil/bytecode-opy.zip' failed
make: *** [_build/oil/bytecode-opy.zip] Error 1
make: *** Deleting file '_build/oil/bytecode-opy.zip'
```

`git log --stat -- pylib/os_.py` shows it was deleted in a5171822f609224c36c24fe9e977453086317910.

**Comment by andychu** [comment]
Can you try `devtools/release.sh quick-oil-tarball` (which runs `make clean-repo`)


https://github.com/oilshell/oil/wiki/Contributing

Unfortunately there are a bunch of dependencies not captured well in the Makefile (which is one of the reasons I want to move to smething else eventually)

**Comment by jyn514** [comment]
Ok that worked. Could you add that to https://github.com/oilshell/oil/wiki/Contributing#three-kinds-of-builds? I'm not sure what parts of that wiki are still necessary and which aren't.
