### ISSUE TITLE
local -n flag not implemented

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#600]
This is a toy script but it might be a good benchmark.

https://git.zx2c4.com/chacha20.sh/plain/chacha20.sh

```
$ osh chacha20.sh 
        local -n state=$1
              ^~
chacha20.sh:55: 'local' doesn't accept flag -n
        local -n stream=$2
              ^~
chacha20.sh:56: 'local' doesn't accept flag -n
        local -n x=$1; shift
              ^~
chacha20.sh:11: 'local' doesn't accept flag -n
        x[$1]=$(( (x[$1] + x[$2]) & 0xffffffff ))
                   ^
chacha20.sh:12: warning: Undefined value in arithmetic context
```

```
$ time bash chacha20.sh 
pass
pass

real    0m1.932s
user    0m1.597s
sys     0m0.493s
```

**Comment by abathur** [comment]
One of the shell libraries I'm looking at patching does this (and one of my own uses `declare -n`), if a real-world testcase is better:

https://github.com/bashup/events/blob/9b4226b906915de7bf882ff807976551aac12a43/bashup.events#L5

You'd need to add something like `event emit test` to trigger it.

If you _do_ use it as a testcase, it may also be interesting to also get the copy from the master branch. The two branches are basically forked versions (3.2+ and 4.4+) with different performance profiles. I get an opaque assertion error when I run `event emit test` against the 3.2+ version:

```
Traceback (most recent call last):
  File "/Users/abathur/work/oil/bin/oil.py", line 919, in <module>
    sys.exit(main(sys.argv))
  File "/Users/abathur/work/oil/bin/oil.py", line 865, in main
    return AppBundleMain(argv)
  File "/Users/abathur/work/oil/bin/oil.py", line 838, in AppBundleMain
    status = ShellMain('osh', argv0, main_argv, login_shell)
  File "/Users/abathur/work/oil/bin/oil.py", line 654, in ShellMain
    status = main_loop.Batch(ex, c_parser, arena, nodes_out=nodes_out)
  File "/Users/abathur/work/oil/core/main_loop.py", line 166, in Batch
    is_return, is_fatal = ex.ExecuteAndCatch(node)
  File "/Users/abathur/work/oil/osh/cmd_exec.py", line 1850, in ExecuteAndCatch
    status = self._Execute(node, fork_external=fork_external)
  File "/Users/abathur/work/oil/osh/cmd_exec.py", line 1795, in _Execute
    status, check_errexit = self._Dispatch(node, fork_external)
  File "/Users/abathur/work/oil/osh/cmd_exec.py", line 1049, in _Dispatch
    status = self._RunSimpleCommand(cmd_val, fork_external)
  File "/Users/abathur/work/oil/osh/cmd_exec.py", line 791, in _RunSimpleCommand
    return self.RunSimpleCommand(cmd_val, fork_external)
  File "/Users/abathur/work/oil/osh/cmd_exec.py", line 860, in RunSimpleCommand
    status = self._RunProc(func_node, argv[1:])
  File "/Users/abathur/work/oil/osh/cmd_exec.py", line 2020, in _RunProc
    status = self._Execute(func_node.body)
  File "/Users/abathur/work/oil/osh/cmd_exec.py", line 1795, in _Execute
    status, check_errexit = self._Dispatch(node, fork_external)
  File "/Users/abathur/work/oil/osh/cmd_exec.py", line 1414, in _Dispatch
    status = self._ExecuteList(node.children)
  File "/Users/abathur/work/oil/osh/cmd_exec.py", line 1817, in _ExecuteList
    status = self._Execute(child)  # last status wins
  File "/Users/abathur/work/oil/osh/cmd_exec.py", line 1795, in _Execute
    status, check_errexit = self._Dispatch(node, fork_external)
  File "/Users/abathur/work/oil/osh/cmd_exec.py", line 1073, in _Dispatch
    status = self._Execute(node.child)
  File "/Users/abathur/work/oil/osh/cmd_exec.py", line 1795, in _Execute
    status, check_errexit = self._Dispatch(node, fork_external)
  File "/Users/abathur/work/oil/osh/cmd_exec.py", line 1700, in _Dispatch
    status = self._ExecuteList(case_arm.action)
  File "/Users/abathur/work/oil/osh/cmd_exec.py", line 1817, in _ExecuteList
    status = self._Execute(child)  # last status wins
  File "/Users/abathur/work/oil/osh/cmd_exec.py", line 1795, in _Execute
    status, check_errexit = self._Dispatch(node, fork_external)
  File "/Users/abathur/work/oil/osh/cmd_exec.py", line 1700, in _Dispatch
    status = self._ExecuteList(case_arm.action)
  File "/Users/abathur/work/oil/osh/cmd_exec.py", line 1817, in _ExecuteList
    status = self._Execute(child)  # last status wins
  File "/Users/abathur/work/oil/osh/cmd_exec.py", line 1795, in _Execute
    status, check_errexit = self._Dispatch(node, fork_external)
  File "/Users/abathur/work/oil/osh/cmd_exec.py", line 1073, in _Dispatch
    status = self._Execute(node.child)
  File "/Users/abathur/work/oil/osh/cmd_exec.py", line 1795, in _Execute
    status, check_errexit = self._Dispatch(node, fork_external)
  File "/Users/abathur/work/oil/osh/cmd_exec.py", line 1014, in _Dispatch
    cmd_val = self.word_ev.EvalWordSequence2(words, allow_assign=True)
  File "/Users/abathur/work/oil/osh/word_eval.py", line 1745, in EvalWordSequence2
    self._EvalWordToParts(w, False, part_vals)  # not double quoted
  File "/Users/abathur/work/oil/osh/word_eval.py", line 1362, in _EvalWordToParts
    self._EvalWordPart(p, part_vals, quoted=quoted, is_subst=is_subst)
  File "/Users/abathur/work/oil/osh/word_eval.py", line 1255, in _EvalWordPart
    self._EvalBracedVarSub(part, part_vals, quoted)
  File "/Users/abathur/work/oil/osh/word_eval.py", line 937, in _EvalBracedVarSub
    raise AssertionError()
AssertionError
```

**Comment by andychu** [comment]
OK thanks I was able to repro the first problem:

```
andy@lisa:~/git/oilshell/oil$ bin/osh -c '. bashup.events; event emit'
        local n='' s=${2:-_};local -n e=bashup_ev["$s"] f=bashup_ev_r["$s"]
                                   ^~
bashup.events:5: 'local' doesn't accept flag -n
```

How can I repro the crash?  `event emit test` gives the same error.

```
andy@lisa:~/git/oilshell/oil$ bin/osh -c '. bashup.events; event emit test'
        local n='' s=${2:-_};local -n e=bashup_ev["$s"] f=bashup_ev_r["$s"]
                                   ^~
bashup.events:5: 'local' doesn't accept flag -n
```

**Comment by andychu** [comment]
OK nevermind I repro'd AssertionError() from master ... let me see.

**Comment by andychu** [comment]
OK the crash is due to `${!f-}` ... I had assumed that if there's a prefix op, the suffix up is "nullary", but it could be "unary" too, e.g. the `-` test operator.

Let me make a separate bug about it.

**Comment by andychu** [comment]
Fixed: https://www.oilshell.org/release/0.8.pre2/
