### ISSUE TITLE
native/libc_test.py fails on OS X

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#611]
I think these were legit differences because we were testing out a lot of fnmatch(), and the libc on OS X behaves differently

Thread on Zulip

e.g. this one https://oilshell.zulipchat.com/#narrow/stream/121540-oil-discuss/topic/building.20dev.20env.20in.20Nix.20.2B.20macOS/near/187785631

**Comment by abathur** [comment]
Sorry--here's the actual output :)

```
building 'libc' extension
clang -UNDEBUG -I/nix/store/sjw2xj6d38x4135gj6j8yygrpb2f39lf-python-2.7.17/include/python2.7 -c native/libc.c -o build/temp.macosx-10.12-x86_64-2.7/native/libc.o
native/libc.c:288:13: warning: using the result of an assignment as a condition without parentheses [-Wparentheses]
  if (match = (regexec(&pat, str, outlen, pmatch, 0) == 0)) {
      ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
native/libc.c:288:13: note: place parentheses around the assignment to silence this warning
  if (match = (regexec(&pat, str, outlen, pmatch, 0) == 0)) {
            ^
      (                                                   )
native/libc.c:288:13: note: use '==' to turn this assignment into an equality comparison
  if (match = (regexec(&pat, str, outlen, pmatch, 0) == 0)) {
            ^
            ==
1 warning generated.
clang -bundle -undefined dynamic_lookup build/temp.macosx-10.12-x86_64-2.7/native/libc.o -L/nix/store/sjw2xj6d38x4135gj6j8yygrpb2f39lf-python-2.7.17/lib -o /Users/abathur/work/oil/libc.so
libc.so: Mach-O 64-bit x86_64 bundle, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL>
F....real	0.100
user	0.200
sys	0.300
.....FF
======================================================================
FAIL: testFnmatch (__main__.LibcTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "native/libc_test.py", line 79, in testFnmatch
    expected, actual, '%r %r -> got %d' % (pat, s, actual))
AssertionError: '\\' '\\' -> got 1

======================================================================
FAIL: testRegexParse (__main__.LibcTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "native/libc_test.py", line 125, in testRegexParse
    self.assertRaises(RuntimeError, libc.regex_parse, '{')
AssertionError: RuntimeError not raised

======================================================================
FAIL: testWcsWidth (__main__.LibcTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "native/libc_test.py", line 199, in testWcsWidth
    self.assertEqual(1, libc.wcswidth("▶️"))
AssertionError: 1 != 2

----------------------------------------------------------------------
Ran 12 tests in 0.002s

FAILED (failures=3)
```
