### ISSUE TITLE
`help` crashes if not given arguments

### ISSUE THREAD

**Issue by jyn514** [oilshell/oil#623]
```
$ bin/osh
osh$ help
Traceback (most recent call last):
  File "/home/joshua/Documents/oil/bin/oil.py", line 962, in <module>
    sys.exit(main(sys.argv))
  File "/home/joshua/Documents/oil/bin/oil.py", line 908, in main
    return AppBundleMain(argv)
  File "/home/joshua/Documents/oil/bin/oil.py", line 881, in AppBundleMain
    status = ShellMain('osh', argv0, main_argv, login_shell)
  File "/home/joshua/Documents/oil/bin/oil.py", line 683, in ShellMain
    prompt_plugin, errfmt)
  File "/home/joshua/Documents/oil/core/main_loop.py", line 95, in Interactive
    is_return, _ = ex.ExecuteAndCatch(node)
  File "/home/joshua/Documents/oil/osh/cmd_exec.py", line 1851, in ExecuteAndCatch
    status = self._Execute(node, fork_external=fork_external)
  File "/home/joshua/Documents/oil/osh/cmd_exec.py", line 1796, in _Execute
    status, check_errexit = self._Dispatch(node, fork_external)
  File "/home/joshua/Documents/oil/osh/cmd_exec.py", line 1050, in _Dispatch
    status = self._RunSimpleCommand(cmd_val, fork_external)
  File "/home/joshua/Documents/oil/osh/cmd_exec.py", line 791, in _RunSimpleCommand
    return self.RunSimpleCommand(cmd_val, fork_external)
  File "/home/joshua/Documents/oil/osh/cmd_exec.py", line 879, in RunSimpleCommand
    return self._RunBuiltin(builtin_id, cmd_val, fork_external)
  File "/home/joshua/Documents/oil/osh/cmd_exec.py", line 513, in _RunBuiltin
    status = self._RunBuiltinAndRaise(builtin_id, cmd_val, fork_external)
  File "/home/joshua/Documents/oil/osh/cmd_exec.py", line 456, in _RunBuiltinAndRaise
    status = builtin_func.Run(cmd_val)
  File "/home/joshua/Documents/oil/osh/builtin_misc.py", line 585, in Run
    span_id=cmd_val.arg_spids[1])
IndexError: list index out of range
```

**Comment by andychu** [comment]
Hm I'm not getting that, but I did change some stuff related to the help build process that may be causing problems.

Are you on master?  I just tried it and it worked for me.  I also tried `build/dev.sh minimal` then `bin/osh`, and it worked (although maybe I didn't clean the build)

The build issue is exposed at the top of builtin_misc.py.  Long story but I didn't want all developers to have CommonMark installed -- I was trying to keep `bin/osh` light and simple.

```
if mylib.PYTHON:
  # Hack because we don't want libcmark.so dependency for build/dev.sh minimal
  try:
    from _devbuild.gen import help_index  # generated file
  except ImportError:
    help_index = None
```

```
andy@lisa ~/git/oilshell/oil (master)$ bin/osh
[osh] lisa ~/git/oilshell/oil$ help
 help 

    help index           # list all help topics
    help index GROUP...  # list help topics in the given groups
    help TOPIC           # show help on a given topic
    help osh-usage       # same as osh --help
    help oil-usage       # same as oil --help

View on the web: http://www.oilshell.org/$VERSION/doc/osh-quick-ref.html
```

**Comment by andychu** [comment]
Whenever you pull the process is to do `build/dev.sh all` (or `build/dev.sh minimal`) and then run `bin/osh`.  I'm not sure if that is entirely clear from the docs.  There is a ton of code generation going on so that's why we need it.

**Comment by jyn514** [comment]
I am on the master branch (commit `512c68eeb0f673fefee23af43abf732fe1eef4db`, release 0.8.pre). Maybe this is a difference between the dev and release versions of osh? Let me try that real quick.

**Comment by jyn514** [comment]
Ok, I'm having trouble with the full release build. I ran `sudo apt install cmark` but I'm still getting `OSError: /usr/local/lib/libcmark.so: cannot open shared object file: No such file or directory`. Is there another package I'm missing?

**Comment by andychu** [comment]
Ah OK sorry I didn't document this:

https://github.com/oilshell/oil/blob/master/doctools/cmark.sh#L12


I guess everyone has been running `build/dev.sh minimal`.  In the last few months `build/dev.sh all` now depends on cmark for documentation.

I will document it later tonight but you should be able to do:

```
doctools/cmark.sh download
doctools/cmark.sh extract
doctools/cmark.sh build
doctools/cmark.sh run-tests
```

**Comment by jyn514** [comment]
After following the steps in https://github.com/oilshell/oil/wiki/Contributing I have a different error:

```
$ devtools/release.sh quick-oil-tarball
# lots of output
{ echo '_build/release-date.txt release-date.txt'; \
  cat build/oil-manifest.txt \
      _build/oil/opy-app-deps.txt; \
  build/actions.sh help-manifest _devbuild/help; \
  build/actions.sh pyc-version-manifest _build/oil/bytecode-opy-manifest.txt; \
} > _build/oil/bytecode-opy-manifest.txt
build/make_zip.py _build/oil/bytecode-opy.zip < _build/oil/bytecode-opy-manifest.txt
cat _build/oil/ovm-dbg _build/oil/bytecode-opy.zip > _bin/oil.ovm-dbg
[bat error]: '_build/oil/ovm-dbg': No such file or directory (os error 2)
Makefile:189: recipe for target '_bin/oil.ovm-dbg' failed
make: *** [_bin/oil.ovm-dbg] Error 1
make: *** Deleting file '_bin/oil.ovm-dbg'
```

**Comment by jyn514** [comment]
Interesting, now `help` no longer crashes. Maybe one of the steps along the way changed something?

```
$ bin/osh
osh$ help
 help 

    help index           # list all help topics
    help index GROUP...  # list help topics in the given groups
    help TOPIC           # show help on a given topic
    help osh-usage       # same as osh --help
    help oil-usage       # same as oil --help

View on the web: http://www.oilshell.org/$VERSION/doc/osh-quick-ref.html
```

**Comment by andychu** [comment]
Hm I'm not sure what happened, but if you didn't touch the repo in awhile, it wouldn't surprise me that `make clean` would be necessary before rebuilding...

**Comment by jyn514** [comment]
This was on a fresh clone of the repo with no build artifacts.

**Comment by andychu** [comment]
Hm I'm not sure what happened... if you can repro it, we can debug it.  Although one thing I can do is put it in Travis to see what happens.

Let's see after this: https://github.com/oilshell/oil/commit/36bbfc8c32c741c73d4aa0d8626fd4a53197f8d7

I updated the wiki page with some info on `re2c` and `cmark` and documented them more too:

https://github.com/oilshell/oil/wiki/Contributing

https://github.com/oilshell/oil/commit/991352dc899a56f691cb1fb6c25a1147d172571b

**Comment by andychu** [comment]
Ah OK it does fail on Travis!  I need to get the output to debug it... was talking about that with @abathur who is working with Nix.

https://travis-ci.org/oilshell/oil/jobs/658076004#L2460

**Comment by andychu** [comment]
I pushed a fix for the crash... It might still fail with exit code 1 though, which makes it fail on Travis.  

The `help` builtin needs more work and I may circle back to this.  Or maybe the Nix build will get rid of this awkward split between `build/dev.sh minimal` and  `all`.  Or I could just switch Travis to `build/dev.sh all` (with some effort)

**Comment by abathur** [comment]
@andychu Yes, I noticed this (and have them in my WIP Nix build) as I've been going through spec test failures (I actually noticed it because --version fails in my nix build, so I grepped around for anything else that was getting loaded).

Not sure you need to worry about spending time to move travis to `build/dev.sh all` at the moment since my work should cover that. I'll catch you on zulip.

**Comment by andychu** [comment]
Related to #42 and #187, because spec tests only do `build/dev.sh minimal` now

**Comment by andychu** [comment]
All spec tests now pass on Travis... So you should be able to use the same tasks to get a working build.  

https://github.com/oilshell/oil/blob/dev/andy-21/services/toil-worker.sh#L80

- tarball-deps: re2c and CommonMark
- spec-deps: all the shells for spec tests

Example:

http://travis-ci.oilshell.org/jobs/2020-03-20__18-34-10.wwz/

-----

I guess I will leave this issue open though since we still have the "minimal" build.  Nix #513 may help with that

**Comment by andychu** [comment]
FWIW, what happens currently with the minimal build:

```
$ bin/osh
[osh] lisa ~/git/oilshell/oil4$ help
  help
  ^~~~
[ interactive ]:1: no help topics match 'help'
```

So at least it doesn't crash.  It is unfortunate that's different than the `build/dev.sh all`.

I think this only affects people working on the `help` builtin.  But if anyone thinks I should get rid of the `minimal` build because it's confusing, I'm open to that feedback.  The whole point of it was that you could get started quickly hacking Oil without fussing with many dependencies!

Though it's true the spec tests have more dependencies, and in many cases you do need them to make changes to Oil.

So I'm open to more feedback on what will make the dev process less painful.  

I think I should clean up some of the spew... the `flag_gen.py` stuff added a bunch of spew.

**Comment by jyn514** [comment]
> I think this only affects people working on the help builtin. But if anyone thinks I should get rid of the minimal build because it's confusing, I'm open to that feedback. The whole point of it was that you could get started quickly hacking Oil without fussing with many dependencies!

> That's because I didn't want to force a CommonMark install, although maybe I should just do that and get rid of the extra complexity. 

I think if it printed a message that help isn't available _because_ you don't have commonmark, that would be helpful. Right now it seems to a new contributor as if there's no `help` available either in the `minimal` or `all` build.

**Comment by jyn514** [comment]
Ok, it looks like `build/dev.sh minimal` already does this, just not the `help` builtin. I missed it the first time because of all the spew. It would be great if `help` also said something.
