### ISSUE TITLE
Osh: Word Splitting

### ISSUE THREAD

**Issue by xPMo** [oilshell/oil#628]
Script:
```bash
IFS=':'; word='a:'
printf '[%s] ' ${word}:b
```
Bash, Dash, etc:
```
[a] [:b]
```
Osh:
```
[a] [\] [b]
```
---

Script:
```bash
IFS=':'; word='a:'
printf '[%s] ' ${word}:
```
Bash, Dash, etc:
```
[a] [:]
```
Osh: *(crashes, stderr)*

```
Traceback (most recent call last):
  File "/home/pmo/Repos/oil/bin/oil.py", line 962, in <module>
    sys.exit(main(sys.argv))
  [...]
  File "/home/pmo/Repos/oil/osh/glob_.py", line 129, in GlobUnescape
    assert i != n - 1, 'Trailing backslash: %r' % s
AssertionError: Trailing backslash: '\\'
```

**Comment by andychu** [comment]
Doh, good catch.  Yes it appears this is related to the `IFS='\'` but I mentioned in the other bug.

This makes fixing that a priority (both bugs can be fixed at once), although it's a little hairy and I'm not sure exactly when.

Keep the bug reports coming in any case!  I haven't gotten any "fundamental language" bugs in awhile, and it helps to catch them early.

**Comment by andychu** [comment]
Hm I'm getting a crash in both cases, with `${word}:` and `${word}:b`.  I haven't gotten:

```
[a] [\] [b]
```

I'm not sure how important it is, but what version of OSH can you reproduce that with?

-----

In any case I'm pretty sure I know how to fix it, but it's a bit hairy.  I have to carry along some booleans further through the word expansion pipeline.

**Comment by xPMo** [comment]
I can't reproduce it anymore, which is bizarre.
