### ISSUE TITLE
Oil expression evaluator shouldn't be "metacircular"

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#636]
We're no longer depending on the CPython runtime.

Instead of `PyObject` we're going to use `runtime_asdl::value_t`

- [ ] Tuples aren't useful without funcs, without tuple keys.  Defer
- [ ] defer: list comprehensions, shouldn't parse
- [x] get rid of lambdas, shouldn't parse.  Maybe do it in `expr_to_ast.py`
  - expression language parser is shared with Tea language, but the evaluator isn't!
  - our evaluator has implicit string -> number coercion rules.  The Tea one will have runtime errors to simulate compile time.
    - although maybe this is an execution flag?  `shopt`
  - maybe: C++ function overloading at runtime?
- [x] defer:  heterogeneous list?   `%(one two)` is alias for `['one', 'two']` ?
- [x] get rid of `Array[T]()`
  - maybe that is better as `%Int[...]`, but in either case we don't have these typed arrays

Fully Recursive changes:

- [ ] `Array(value_t* elems)`
- [ ] `Dict(dict[str, value_t] items)`

Then we can do the List change, and maybe List comprehensions?

Things to ADD:

- [x] Block expressions?  -- now `var b = ^(echo one; echo two)`

**Comment by andychu** [comment]
- Hm yeah we should probably get rid of list comprehensions and generator expressions

**Comment by andychu** [comment]
These are related to how we're reusing CPython:

- #1092
- #954 
- #840 

And another one, due to Python's dict being converted to `value.AssocArray`

```
$ bin/oil -c 'var d ={name: [1,2,3]}; echo ${d[@]}'
Traceback (most recent call last):
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 360, in <module>
    sys.exit(main(sys.argv))
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 303, in main
    return AppBundleMain(argv)
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 280, in AppBundleMain
    loader, line_input)
  File "/home/andy/git/oilshell/oil/core/shell.py", line 683, in Main
    cmd_flags=cmd_eval.IsMainProgram)
  File "/home/andy/git/oilshell/oil/core/main_loop.py", line 332, in Batch
    is_return, is_fatal = cmd_ev.ExecuteAndCatch(node, cmd_flags=cmd_flags)
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1633, in ExecuteAndCatch
    status = self._Execute(node)
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1471, in _Execute
    status = self._Dispatch(node, cmd_st)
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1033, in _Dispatch
    status = self._ExecuteList(node.children)
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1536, in _ExecuteList
    status = self._Execute(child)
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1471, in _Execute
    status = self._Dispatch(node, cmd_st)
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 660, in _Dispatch
    cmd_val = self.word_ev.EvalWordSequence2(words, allow_assign=True)
  File "/home/andy/git/oilshell/oil/osh/word_eval.py", line 2186, in EvalWordSequence2
    return self.SimpleEvalWordSequence2(words, allow_assign)
  File "/home/andy/git/oilshell/oil/osh/word_eval.py", line 2168, in SimpleEvalWordSequence2
    strs.append(''.join(tmp))  # no split or glob
TypeError: sequence item 0: expected string, list found

```

**Comment by andychu** [comment]
Here's one in the old scheme

```
$ oil -c 'var a = %(a); var b = %(b); pp cell a;  setvar c = a++b; pp cell c; echo ${#c[@]}'
a = (cell exported:F readonly:F nameref:F val:(value.MaybeStrArray strs:[a]))
c = (cell exported:F readonly:F nameref:F val:(value.Obj obj:['a', 'b']))

```

**Comment by andychu** [comment]
`ysh/expr_eval.py` is not typed with `value_t` !

And translated

**Comment by andychu** [comment]
Released, announcement forthcoming - https://www.oilshell.org/release/0.17.0/
