### ISSUE TITLE
Failing tests on macOS Sierra

### ISSUE THREAD

**Issue by belak** [oilshell/oil#68]
The `master` branch doesn't currently build. It looks like some tests are failing.

```
% ./build/dev.sh minimal
Wrote _build/osh-quick-ref/ and _devbuild/gen/osh_help.py
Wrote _build/doc/osh-quick-ref.html
Wrote _devbuild/gen/osh_asdl.py
Wrote _devbuild/gen/runtime_asdl.py
running build
running build_ext
libc.so -> _devbuild/py-ext/x86_64/libc.so
libc.so: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit bundle x86_64] [i386:Mach-O bundle i386]
libc.so (for architecture x86_64):	Mach-O 64-bit bundle x86_64
libc.so (for architecture i386):	Mach-O bundle i386
['__doc__', '__file__', '__name__', '__package__', 'fnmatch', 'glob', 'regex_match', 'regex_parse']
FGLOB
['__init__.py']
[]
[]
.Error compiling regex: Invalid use of repetition operators such as using '*' as the first character.
Error compiling regex: Trailing backslash.
F.
======================================================================
FAIL: testFnmatch (__main__.LibcTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "native/libc_test.py", line 44, in testFnmatch
    self.assertEqual(expected, actual)
AssertionError: 0 != 1L

======================================================================
FAIL: testRegex (__main__.LibcTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "native/libc_test.py", line 60, in testRegex
    self.assertEqual(False, libc.regex_parse('{'))
AssertionError: False != True

----------------------------------------------------------------------
Ran 4 tests in 0.001s

FAILED (failures=2)
```

Current versions:
* macOS Sierra 10.12.6
* oil commit d20061bad9f09ef747df89a4cd4b43412b2ff0d4

Let me know if you need anything else to reproduce this.

**Comment by andychu** [comment]
OK thanks for the report.  I don't have a Mac dev env right now, but someone told me Travis supports Mac, so maybe I can reproduce there.

**Comment by andychu** [comment]
Actually I'm going to move this to issue #70, because Mac is sort of a special case (you can't install it for free in the cloud AFAIK.)  Please follow that if you're interested.

The first step is to get the release tarball building and running.  I'm not sure the Python unit tests will ever work.  (The plan is to move away from Python, although that might not happen for a year.)

**Comment by BatmanAoD** [comment]
I am having almost exactly the same error on a 64-bit Debian Jessie (8.10) virtual machine. Maybe it's worth reopening?

```
Wrote _devbuild/osh-quick-ref/ and _devbuild/gen/osh_help.py
Wrote _build/doc/osh-quick-ref.html
Wrote _devbuild/gen/types_asdl.py
Wrote _devbuild/gen/osh_asdl.py
Wrote _devbuild/gen/runtime_asdl.py
running build
running build_ext
building 'libc' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -UNDEBUG -I/usr/include/python2.7 -c native/libc.c -o build/temp.linux-x86_64-2.7/native/libc.o
creating _devbuild/py-ext/x86_64
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/native/libc.o -o _devbuild/py-ext/x86_64/libc.so
‘libc.so’ -> ‘_devbuild/py-ext/x86_64/libc.so’
libc.so: symbolic link to _devbuild/py-ext/x86_64/libc.so
['__doc__', '__file__', '__name__', '__package__', 'fnmatch', 'glob', 'regex_match', 'regex_parse']
.GLOB
['__init__.py']
[]
[]
.Error compiling regex: Invalid use of repetition operators such as using '*' as the first character.
Error compiling regex: Trailing backslash.
Error compiling regex: Invalid use of repetition operators such as using '*' as the first character.
Invalid regex at runtime
-1
..
----------------------------------------------------------------------
Ran 4 tests in 0.001s

OK
```

A quick smoke test of `osh` itself showed that the compile did produce a working binary.

The spec test suite passed, but the unit test suite had additional errors. I didn't look too closely at them, though.

**Comment by Yorwba** [comment]
The last line is `OK`, so the tests actually passed. Like you, I thought that those error messages were test failures when I first ran the script, but they are actually expected output by some tests that intentionally attempt invalid operations.

**Comment by BatmanAoD** [comment]
...ah. I thought it was a test framework issue, so I didn't trust the `OK` at the end.
