### ISSUE TITLE
Error with backslashes in unquoted variables with globbing off

### ISSUE THREAD

**Issue by Crestwave** [oilshell/oil#698]
Required for #679. 

```bash
osh$ var='\'
osh$ set -f
osh$ echo $var
Traceback (most recent call last):
  File "/home/usr/oil/bin/oil.py", line 996, in <module>
    sys.exit(main(sys.argv))
  File "/home/usr/oil/bin/oil.py", line 942, in main
    return AppBundleMain(argv)
  File "/home/usr/oil/bin/oil.py", line 915, in AppBundleMain
    status = ShellMain('osh', argv0, main_argv, login_shell)
  File "/home/usr/oil/bin/oil.py", line 717, in ShellMain
    prompt_plugin, errfmt)
  File "/home/usr/oil/core/main_loop.py", line 98, in Interactive
    is_return, _ = cmd_ev.ExecuteAndCatch(node)
  File "/home/usr/oil/osh/cmd_eval.py", line 1439, in ExecuteAndCatch
    status = self._Execute(node)
  File "/home/usr/oil/osh/cmd_eval.py", line 1323, in _Execute
    status, check_errexit = self._Dispatch(node)
  File "/home/usr/oil/osh/cmd_eval.py", line 535, in _Dispatch
    cmd_val = self.word_ev.EvalWordSequence2(words, allow_assign=True)
  File "/home/usr/oil/osh/word_eval.py", line 1850, in EvalWordSequence2
    self._EvalWordFrame(frame, strs)
  File "/home/usr/oil/osh/word_eval.py", line 1611, in _EvalWordFrame
    self.globber.Expand(a, argv)
  File "/home/usr/oil/osh/glob_.py", line 373, in Expand
    out.append(GlobUnescape(arg))
  File "/home/usr/oil/osh/glob_.py", line 129, in GlobUnescape
    assert i != n - 1, 'Trailing backslash: %r' % s
AssertionError: Trailing backslash: '\\'
```

**Comment by andychu** [comment]
OK thanks, this is also #628 , need to fix this!

**Comment by andychu** [comment]
I technically fixed this specific case, although there are some other bugs in this area and code needs a lot of work in general (see commit description)

**Comment by Crestwave** [comment]
Yes, this still isn't enough for #679: 

```bash
$ var='\e'
$ set -f
$ echo $var
\e
```

```bash
osh$ var='\e'
osh$ set -f
osh$ echo $var
e
```

**Comment by andychu** [comment]
Actually I  fixed this without doing the big refactoring I was afraid of!  woohoo

**Comment by Crestwave** [comment]
Great! Not sure if there are some cornercases where it doesn't work without #701 resolved, but it now runs on my machine with some upstreamable patches! I've opened a PR: https://github.com/dylanaraps/neofetch/pull/1442

**Comment by andychu** [comment]
Awesome, thanks for sending the patch!  I was about to check see what was left in the patch but you beat me to it :)
