### ISSUE TITLE
python traceback while building Oil

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#809]
We don't have a full repro on this, but in case it comes up again

```
Removing _devbuild/help/*
Traceback (most recent call last):
File "doctools/cmark.py", line 353, in <module>
main(sys.argv)
File "doctools/cmark.py", line 349, in main
doc_html.Footer(meta, sys.stdout)
File "/home/oil/oil/doctools/doc_html.py", line 82, in Footer
''' % meta)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 58: ordinal not in range(128)
```

from Diego on Zulip

**Comment by dcghub** [comment]
Just for the record, this was after running `build/dev.sh all`

**Comment by dcghub** [comment]
OK, I have some clues about the problem. It is not that my editor is inserting UTF-8 chars - file says it's ascii, and the build fails even when trying to build your master branch.

I should have noticed it before: My locale is set to es_ES.UTF-8 , and my repo is in a directory named "código". I don't know what made it fail and work at random times in the past, but right now it will fail if I build it with the default "build/dev.sh all", and it will work with locale set to LC_ALL='C'. So it seems to be some locale issue.
