### ISSUE TITLE
crash with eval ${!undef-}

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#956]
Reported by Travis Everett: https://oilshell.zulipchat.com/#narrow/stream/121540-oil-discuss/topic/assertion.20error.2C.20maybe.20missing.20token.2Fpart.20tag.3F

```
$ bin/osh -c 'eval ${!e-}'
Traceback (most recent call last):
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 358, in <module>
    sys.exit(main(sys.argv))
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 301, in main
    return AppBundleMain(argv)
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 261, in AppBundleMain
    loader, line_input)
  File "/home/andy/git/oilshell/oil/core/shell.py", line 677, in Main
    cmd_flags=cmd_eval.IsMainProgram)
  File "/home/andy/git/oilshell/oil/core/main_loop.py", line 324, in Batch
    is_return, is_fatal = cmd_ev.ExecuteAndCatch(node, cmd_flags=cmd_flags)
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1490, in ExecuteAndCatch
    status = self._Execute(node)
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1337, in _Execute
    status, check_errexit = self._Dispatch(node, pipeline_st)
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 599, in _Dispatch
    cmd_val = self.word_ev.EvalWordSequence2(words, allow_assign=True)
  File "/home/andy/git/oilshell/oil/osh/word_eval.py", line 1960, in EvalWordSequence2
    self._EvalWordToParts(w, False, part_vals)  # not double quoted
  File "/home/andy/git/oilshell/oil/osh/word_eval.py", line 1553, in _EvalWordToParts
    self._EvalWordPart(p, part_vals, quoted=quoted, is_subst=is_subst)
  File "/home/andy/git/oilshell/oil/osh/word_eval.py", line 1438, in _EvalWordPart
    self._EvalBracedVarSub(part, part_vals, quoted)
  File "/home/andy/git/oilshell/oil/osh/word_eval.py", line 1230, in _EvalBracedVarSub
    val = self._ApplyPrefixOp(val, part.prefix_op, part.token)
  File "/home/andy/git/oilshell/oil/osh/word_eval.py", line 671, in _ApplyPrefixOp
    assert val.tag != value_e.Undef
AssertionError

```

**Comment by andychu** [comment]
https://www.oilshell.org/blog/2021/07/release-0.8.12.html
