### ISSUE TITLE
osh throws an `OverflowError` & dumps a stack trace on `(return 2147483648)` or `(exit 2147483648)`

### ISSUE THREAD

**Issue by bb010g** [oilshell/oil#996]
Approximately equivalent to `(return $((2 ** 31)))`. Discovered in https://gist.github.com/bb010g/8ac1a2068d84176fc998422a1d200258/21929e28f647c23fa1159c29f451f82f483d9059#file-500-stdout-txt-L651 .

```
( return i32; ): 2147483647 -> 255, -2147483648 ->   0, Traceback (most recent call last):
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 328, in _cpython_main_hook
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 301, in main
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 292, in AppBundleMain
  File "/home/andy/git/oilshell/oil/core/shell.py", line 675, in Main
  File "/home/andy/git/oilshell/oil/core/main_loop.py", line 330, in Batch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1498, in ExecuteAndCatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1345, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 988, in _Dispatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1401, in _ExecuteList
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1345, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 644, in _Dispatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1345, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 636, in _Dispatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 477, in _RunSimpleCommand
  File "/home/andy/git/oilshell/oil/core/executor.py", line 224, in RunSimpleCommand
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1642, in RunProc
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1345, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 998, in _Dispatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1401, in _ExecuteList
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1345, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 644, in _Dispatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1345, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1113, in _Dispatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1345, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 993, in _Dispatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1401, in _ExecuteList
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1345, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 644, in _Dispatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1345, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 636, in _Dispatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 477, in _RunSimpleCommand
  File "/home/andy/git/oilshell/oil/core/executor.py", line 224, in RunSimpleCommand
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1642, in RunProc
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1345, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 674, in _Dispatch
  File "/home/andy/git/oilshell/oil/core/executor.py", line 330, in RunSubshell
  File "/home/andy/git/oilshell/oil/core/process.py", line 940, in RunWait
  File "/home/andy/git/oilshell/oil/core/process.py", line 880, in Start
  File "/home/andy/git/oilshell/oil/core/process.py", line 723, in Run
OverflowError: signed integer is greater than maximum
FATAL: couldn't import from app bundle '/nix/store/iz02wfvpiy92b54mjrz8110fs165n477-oil-0.9.2/bin/osh' (1)
Stripping the oil.ovm binary may cause this error.
See https://github.com/oilshell/oil/issues/47
2147483648 ->   1,
```

```
Traceback (most recent call last):
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 328, in _cpython_main_hook
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 301, in main
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 292, in AppBundleMain
  File "/home/andy/git/oilshell/oil/core/shell.py", line 675, in Main
  File "/home/andy/git/oilshell/oil/core/main_loop.py", line 330, in Batch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1498, in ExecuteAndCatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1345, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 988, in _Dispatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1401, in _ExecuteList
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1345, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 644, in _Dispatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1345, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 636, in _Dispatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 477, in _RunSimpleCommand
  File "/home/andy/git/oilshell/oil/core/executor.py", line 224, in RunSimpleCommand
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1642, in RunProc
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1345, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 998, in _Dispatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1401, in _ExecuteList
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1345, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 644, in _Dispatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1345, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1113, in _Dispatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1345, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 993, in _Dispatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1401, in _ExecuteList
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1345, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 644, in _Dispatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1345, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 636, in _Dispatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 477, in _RunSimpleCommand
  File "/home/andy/git/oilshell/oil/core/executor.py", line 224, in RunSimpleCommand
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1642, in RunProc
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1345, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 674, in _Dispatch
  File "/home/andy/git/oilshell/oil/core/executor.py", line 330, in RunSubshell
  File "/home/andy/git/oilshell/oil/core/process.py", line 940, in RunWait
  File "/home/andy/git/oilshell/oil/core/process.py", line 880, in Start
  File "/home/andy/git/oilshell/oil/core/process.py", line 723, in Run
OverflowError: signed integer is less than minimum
FATAL: couldn't import from app bundle '/nix/store/iz02wfvpiy92b54mjrz8110fs165n477-oil-0.9.2/bin/osh' (1)
Stripping the oil.ovm binary may cause this error.
See https://github.com/oilshell/oil/issues/47
-4294967296 ->   1
```

```
Traceback (most recent call last):
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 328, in _cpython_main_hook
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 301, in main
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 292, in AppBundleMain
  File "/home/andy/git/oilshell/oil/core/shell.py", line 675, in Main
  File "/home/andy/git/oilshell/oil/core/main_loop.py", line 330, in Batch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1498, in ExecuteAndCatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1345, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 988, in _Dispatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1401, in _ExecuteList
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1345, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 644, in _Dispatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1345, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 636, in _Dispatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 477, in _RunSimpleCommand
  File "/home/andy/git/oilshell/oil/core/executor.py", line 224, in RunSimpleCommand
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1642, in RunProc
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1345, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 998, in _Dispatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1401, in _ExecuteList
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1345, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 644, in _Dispatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1345, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1113, in _Dispatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1345, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 993, in _Dispatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1401, in _ExecuteList
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1345, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 644, in _Dispatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1345, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 636, in _Dispatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 477, in _RunSimpleCommand
  File "/home/andy/git/oilshell/oil/core/executor.py", line 224, in RunSimpleCommand
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1642, in RunProc
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1345, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 674, in _Dispatch
  File "/home/andy/git/oilshell/oil/core/executor.py", line 330, in RunSubshell
  File "/home/andy/git/oilshell/oil/core/process.py", line 940, in RunWait
  File "/home/andy/git/oilshell/oil/core/process.py", line 880, in Start
  File "/home/andy/git/oilshell/oil/core/process.py", line 723, in Run
OverflowError: Python int too large to convert to C long
FATAL: couldn't import from app bundle '/nix/store/iz02wfvpiy92b54mjrz8110fs165n477-oil-0.9.2/bin/osh' (1)
Stripping the oil.ovm binary may cause this error.
See https://github.com/oilshell/oil/issues/47
9223372036854775808 ->   1,
```

**Comment by andychu** [comment]
Hm I can't repro this

```
$  osh -c 'return $(( 2** 31 ))'; echo $?
0
```

Can you give an exact repro?

**Comment by andychu** [comment]
Also tried
```

$ osh -c '(return 2147483648)'
$ osh -c '(exit 2147483648)'
```

doesn't crash?  

I'm running with 0.9.3 but I doubt that makes a difference vs. 0.9.2

**Comment by bb010g** [comment]
```
$ nix shell 'nixpkgs/ee084c02040e864eeeb4cf4f8538d92f7c675671#oil' -c osh -c 'foo() ( return "$@"; ); foo 2147483648'
Traceback (most recent call last):
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 328, in _cpython_main_hook
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 301, in main
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 292, in AppBundleMain
  File "/home/andy/git/oilshell/oil/core/shell.py", line 675, in Main
  File "/home/andy/git/oilshell/oil/core/main_loop.py", line 330, in Batch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1498, in ExecuteAndCatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1345, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 988, in _Dispatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1401, in _ExecuteList
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1345, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 636, in _Dispatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 477, in _RunSimpleCommand
  File "/home/andy/git/oilshell/oil/core/executor.py", line 224, in RunSimpleCommand
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1642, in RunProc
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1345, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 674, in _Dispatch
  File "/home/andy/git/oilshell/oil/core/executor.py", line 330, in RunSubshell
  File "/home/andy/git/oilshell/oil/core/process.py", line 940, in RunWait
  File "/home/andy/git/oilshell/oil/core/process.py", line 880, in Start
  File "/home/andy/git/oilshell/oil/core/process.py", line 723, in Run
OverflowError: signed integer is greater than maximum
FATAL: couldn't import from app bundle '/nix/store/iz02wfvpiy92b54mjrz8110fs165n477-oil-0.9.2/bin/oil.ovm' (1)
Stripping the oil.ovm binary may cause this error.
See https://github.com/oilshell/oil/issues/47
(1) $ nix shell 'nixpkgs/ee084c02040e864eeeb4cf4f8538d92f7c675671#oil' -c osh -c 'foo() ( exit "$@"; ); foo 2147483648'
Traceback (most recent call last):
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 328, in _cpython_main_hook
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 301, in main
  File "/home/andy/git/oilshell/oil/bin/oil.py", line 292, in AppBundleMain
  File "/home/andy/git/oilshell/oil/core/shell.py", line 675, in Main
  File "/home/andy/git/oilshell/oil/core/main_loop.py", line 330, in Batch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1498, in ExecuteAndCatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1345, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 988, in _Dispatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1401, in _ExecuteList
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1345, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 636, in _Dispatch
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 477, in _RunSimpleCommand
  File "/home/andy/git/oilshell/oil/core/executor.py", line 224, in RunSimpleCommand
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1642, in RunProc
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 1345, in _Execute
  File "/home/andy/git/oilshell/oil/osh/cmd_eval.py", line 674, in _Dispatch
  File "/home/andy/git/oilshell/oil/core/executor.py", line 330, in RunSubshell
  File "/home/andy/git/oilshell/oil/core/process.py", line 940, in RunWait
  File "/home/andy/git/oilshell/oil/core/process.py", line 880, in Start
  File "/home/andy/git/oilshell/oil/core/process.py", line 723, in Run
OverflowError: signed integer is greater than maximum
FATAL: couldn't import from app bundle '/nix/store/iz02wfvpiy92b54mjrz8110fs165n477-oil-0.9.2/bin/oil.ovm' (1)
Stripping the oil.ovm binary may cause this error.
See https://github.com/oilshell/oil/issues/47
(1) $
```

**Comment by andychu** [comment]
This is now fixed, thanks for the report!  Will be out with the next release, or you can also test it at HEAD if interested.

**Comment by andychu** [comment]
Released! https://www.oilshell.org/blog/2021/11/release-0.9.4.html  

Thanks for the testing!
